import type { LibraryCategory, LibrarySeverity } from './library';

export const categoryLabelsEn: Record<LibraryCategory, string> = {
  naehrstoffmangel: 'Nutrient Deficiency',
  naehrstoffueberschuss: 'Nutrient Excess',
  schaedlinge: 'Pests',
  krankheiten: 'Diseases',
  umweltprobleme: 'Environmental Issues',
};

export const severityLabelsEn: Record<LibrarySeverity, string> = {
  niedrig: 'Low',
  mittel: 'Medium',
  hoch: 'High',
  kritisch: 'Critical',
};

export const libraryEntriesEn: Record<
  string,
  {
    name: string;
    categoryLabel: string;
    symptoms: string[];
    causes: string[];
    treatment: string[];
    prevention: string[];
  }
> = {
  // ── Nutrient Deficiencies ──────────────────────────────────────
  'n-stickstoff': {
    name: 'Nitrogen Deficiency (N)',
    categoryLabel: 'Nutrient Deficiency',
    symptoms: [
      'Uniform yellowing of LOWER/OLD leaves (entire leaf including veins)',
      'Leaves become soft/limp, fall off – plant looks "skeletal" at the bottom',
      'Entire plant turns light green, slow growth',
      'Stems may turn reddish',
      'Most common deficiency! Biomass loss up to 50% possible (Cockson et al. 2019)',
    ],
    causes: [
      'EC/nutrient concentration too low – most common cause',
      'pH outside optimal range (soil 6.0–7.0, coco 5.8–6.2)',
      'Depleted substrate, excessive flushing',
      'Root problems (overwatering, root rot)',
    ],
    treatment: [
      'Increase EC to manufacturer recommendation',
      'Quick fix: foliar spray with urea 0.5%',
      'Correct pH to 6.0–6.5 (soil) or 5.8–6.0 (coco)',
      'Remove severely yellowed leaves, leave mildly affected ones',
    ],
    prevention: [
      'Measure EC regularly and follow feeding schedule',
      'Check pH with every watering',
      'In flower: reduce N but do NOT eliminate it',
      'Slight yellowing in the last 2 weeks of flower is NORMAL (senescence)',
    ],
  },
  'n-phosphor': {
    name: 'Phosphorus Deficiency (P)',
    categoryLabel: 'Nutrient Deficiency',
    symptoms: [
      'Dark green to blue-green, DULL/matte leaves (loss of shine!)',
      'Olive-green, sunken-looking spots on old leaves (early stage)',
      'Purple stems and petioles (advanced stage)',
      'Lower leaves turn bronze/brown and fall off',
      'Poor flower/root development, small buds',
    ],
    causes: [
      'pH outside the narrow optimal range (P has a tight range!)',
      'Cold temperatures <15°C severely block P uptake',
      'Fe/Zn excess locks out phosphorus',
      'Too little phosphorus in the fertilizer (especially in flower)',
    ],
    treatment: [
      'Correct pH to 6.0–6.5 (soil)',
      'Add mono-potassium phosphate or bloom booster',
      'Keep root zone warm (>18°C)',
      'Mycorrhizal fungi improve P uptake by up to 30%',
      'Tip: Genetically purple stems are SHINY – P deficiency stems are DULL',
    ],
    prevention: [
      'Ensure temperature >18°C at the root zone',
      'Keep pH stable – P has the narrowest availability range of all macronutrients',
      'Use bloom fertilizer with sufficient P during flowering',
      'Do not over-supplement Fe/Zn',
    ],
  },
  'n-kalium': {
    name: 'Potassium Deficiency (K)',
    categoryLabel: 'Nutrient Deficiency',
    symptoms: [
      'Rusty brown marginal necrosis on lower/old leaves – starts at serrated edges',
      'Edges first YELLOW, then BROWN/crispy/dead (dry, papery tissue)',
      'Progresses from bottom to top, entire leaf margin affected',
      'Weak/brittle stems, increased susceptibility to disease',
      'DIFFERENCE from nutrient burn: K = entire margin, burn = only tips 1–3mm!',
    ],
    causes: [
      'K demand increases MASSIVELY in flower – most common deficiency in bloom!',
      'Ca/Mg excess blocks K uptake (antagonism)',
      'pH outside optimal range',
      'Overwatering or depleted substrate',
    ],
    treatment: [
      'Use potassium sulfate or K-heavy bloom fertilizer',
      'Correct pH to 6.0–6.5 (soil)',
      'Temporarily reduce Ca/Mg supplementation',
      'Test runoff EC – flush and start fresh nutrient solution if needed',
    ],
    prevention: [
      'Use bloom fertilizer with high K content during flowering',
      'Measure EC and runoff regularly',
      'Watch for nutrient antagonism: too much Ca/Mg inhibits K',
      'Do not deplete substrate through excessive flushing',
    ],
  },
  'n-kalzium': {
    name: 'Calcium Deficiency (Ca)',
    categoryLabel: 'Nutrient Deficiency',
    symptoms: [
      'Randomly distributed brown/black spots on NEW leaves (immobile!)',
      'Deformed new growth – narrower at the base, curled',
      'Brittle stems, leaf tips hook',
      'Death of the growing tip in severe cases – increased side branching',
      'In coco: CalMag supplementation is MANDATORY!',
    ],
    causes: [
      'pH too low (<6.0 in soil) – Ca is poorly absorbed at acidic pH',
      'Coco substrate binds Ca at cation exchange sites',
      'RO water without CalMag supplement',
      'K/Mg excess blocks Ca (antagonism)',
    ],
    treatment: [
      'Use CalMag supplement from the same manufacturer as your base nutrients',
      'Raise pH to 6.2–6.5 (soil)',
      'Keep humidity at 40–60% – promotes transpiration and Ca transport',
      'Ensure good air circulation',
    ],
    prevention: [
      'In coco: ALWAYS supplement CalMag',
      'With RO water: CalMag is mandatory',
      'Keep pH stable above 6.0',
      'Do not overdose K/Mg – Ca uptake will be inhibited',
    ],
  },
  'n-magnesium': {
    name: 'Magnesium Deficiency (Mg)',
    categoryLabel: 'Nutrient Deficiency',
    symptoms: [
      'Interveinal chlorosis on LOWER/OLD leaves – "skeleton pattern" (veins DEEP green, tissue between yellow)',
      'STRONG contrast between green veins and yellow tissue ("fishbone pattern")',
      'Edges may turn reddish/purple, rusty spots develop over time',
      'Common during flowering and in coco substrate',
      'NOTE: Slightly greener veins on an otherwise yellow leaf = more likely N deficiency, NOT Mg!',
    ],
    causes: [
      'pH too low (<5.8 in coco, <6.0 in soil) – Mg lockout',
      'K excess inhibits Mg uptake (K-Mg antagonism – very common!)',
      'Coco substrate binds Mg',
      'Low-lime/soft water or RO water',
    ],
    treatment: [
      'Epsom salt 1–2 g/L as root drench',
      'Use CalMag supplement from the same manufacturer',
      'Foliar spray with Epsom salt (1 tsp/liter) as a quick fix',
      'Correct pH to 6.0–6.5',
      'Check K dosage and reduce if needed',
    ],
    prevention: [
      'ALWAYS use CalMag with coco and RO water',
      'Do not let pH drop below 5.8 (coco) or 6.0 (soil)',
      'Do not overdose K – most common trigger for Mg deficiency',
      'Keep substrate temperature above 18°C',
    ],
  },
  'n-eisen': {
    name: 'Iron Deficiency (Fe)',
    categoryLabel: 'Nutrient Deficiency',
    symptoms: [
      'Interveinal chlorosis on NEW/UPPER leaves – sharp green vein network on yellow background',
      'In severe cases: leaves turn almost WHITE/bleached',
      'Affects ONLY new leaves (immobile!) – THIS distinguishes it from Mg deficiency',
      'New growth weak, shoot tips slowed',
      'True Fe deficiency is RARE – usually it is pH lockout (pH >6.5)!',
    ],
    causes: [
      'pH too high (>6.5) – most common cause! Fe is blocked at high pH',
      'Mn/Zn/Cu excess or P excess blocks Fe',
      'Overwatering / poor drainage',
      'Hard water or lime-rich substrates',
    ],
    treatment: [
      'Lower pH to 5.8–6.5 – often that alone is enough!',
      'Fe-EDDHA chelate (stable up to pH 9, best choice at high pH)',
      'Foliar spray: Fe-EDTA for rapid uptake',
      'Improve drainage, reduce P if antagonism is suspected',
    ],
    prevention: [
      'Keep pH stable at 5.8–6.5 – most important measure',
      'Use chelate-based fertilizers (EDDHA > DTPA > EDTA)',
      'Do not overwater, ensure good drainage',
      'Do not over-lime the substrate',
    ],
  },
  'n-mangan': {
    name: 'Manganese Deficiency (Mn)',
    categoryLabel: 'Nutrient Deficiency',
    symptoms: [
      'Interveinal chlorosis on young/upper leaves (milder than Fe)',
      'Tan/light brown speckles on the leaf surface ("speckled pattern")',
      'Papery, thin texture of affected leaves',
      'Spots can merge as the deficiency progresses',
      'Growth slowdown in severe cases',
    ],
    causes: [
      'pH too high (>6.5 in soil, >6.0 in coco/hydro)',
      'Iron excess (Fe-Mn antagonism)',
      'Overwatering / poor drainage (anaerobic conditions)',
      'Lime-rich substrates or hard water',
    ],
    treatment: [
      'Lower pH to optimal range (soil 6.0–6.5, coco 5.8–6.0)',
      'Foliar spray with manganese chelate (EDTA) 0.05–0.1%',
      'Optimize watering – do not keep substrate constantly wet',
      'Reduce Fe supplementation if antagonism is suspected',
      'Be patient: existing damage will NOT recover, only new growth will show improvement',
    ],
    prevention: [
      'Measure pH regularly and keep it in the optimal range',
      'Balanced micronutrient supply (do not overdose any single nutrient)',
      'Ensure good drainage',
      'Test tap water for carbonate hardness',
    ],
  },
  'n-zink': {
    name: 'Zinc Deficiency (Zn)',
    categoryLabel: 'Nutrient Deficiency',
    symptoms: [
      'Stunted new growth with tiny, bunched leaves ("rosetting")',
      'Severely shortened internodes – plant looks compact/dwarfed',
      'Interveinal chlorosis, more patchy than iron deficiency',
      'Twisted, wavy leaf edges',
      'In severe cases: necrotic spots on young leaves',
    ],
    causes: [
      'pH too high (>7.0)',
      'Phosphorus excess locks out zinc (P-Zn antagonism – common mistake!)',
      'Alkaline/lime-rich substrates',
      'Excessive Fe or Cu supplementation',
    ],
    treatment: [
      'Correct pH to 6.0–6.5 (soil) or 5.8–6.0 (coco)',
      'Reduce phosphorus if P excess is present',
      'Foliar spray: zinc chelate (EDTA) 0.05–0.1%',
      'Zinc sulfate via root drench (0.5–1 g/L)',
      'Monitor new growth – old leaves will NOT recover',
    ],
    prevention: [
      'Avoid P over-fertilization (common mistake during bloom!)',
      'Keep pH stable in the slightly acidic range',
      'Use quality chelate fertilizer with all micronutrients',
    ],
  },
  'n-schwefel': {
    name: 'Sulfur Deficiency (S)',
    categoryLabel: 'Nutrient Deficiency',
    symptoms: [
      'Uniform yellowing of NEW/UPPER leaves – veins yellow WITH the tissue (no interveinal pattern!)',
      'Affected leaves remain FIRM and upright (no wilting)',
      'Purple discoloration of stems possible',
      'Growth slowdown, thin/brittle stems',
      'In severe cases: small necrotic spots',
    ],
    causes: [
      'pH >7.5 (alkaline)',
      'Use of RO water without S supplementation',
      'Sulfur-poor organic substrates',
      'Extremely filtered/soft water',
    ],
    treatment: [
      'Correct pH (lower to 6.0–6.5)',
      'Epsom salt (magnesium sulfate) 1–2 g/L as root drench',
      'Potassium sulfate as an alternative',
      'Foliar spray with Epsom salt 0.5 g/L for rapid uptake',
      'With RO water: add a CalMag product that contains sulfur',
    ],
    prevention: [
      'With RO water always use sulfur-containing additives',
      'Do not let pH rise above 7.0',
      'Consider gypsum (calcium sulfate) as a substrate amendment',
    ],
  },
  'n-bor': {
    name: 'Boron Deficiency (B)',
    categoryLabel: 'Nutrient Deficiency',
    symptoms: [
      'Deformed, twisted shoot tips',
      'Hollow stems – almost unique sign of boron deficiency!',
      'Rough, thick, brittle leaf surface',
      'Brittle petioles that break easily',
      'Poor flower development, airy buds',
    ],
    causes: [
      'pH >6.5 (alkaline)',
      'Overwatering (boron is easily leached)',
      'Calcium excess (Ca-B antagonism)',
      'Low humidity (<30% RH)',
    ],
    treatment: [
      'Lower pH to 6.0–6.5',
      'Boric acid solution: VERY CAREFULLY, only 0.25–0.5 g/L (extremely narrow tolerance!)',
      'Borax as a milder alternative to boric acid',
      'Optimize watering (less frequent, but more thorough)',
      'WARNING: Overdosing quickly leads to boron toxicity!',
    ],
    prevention: [
      'Keep pH stable in the slightly acidic range',
      'Do not over-supplement calcium',
      'Use a quality micronutrient mix',
      'Never "more is better" – extremely narrow range between deficiency and toxicity',
    ],
  },
  'n-kupfer': {
    name: 'Copper Deficiency (Cu)',
    categoryLabel: 'Nutrient Deficiency',
    symptoms: [
      'Blue-green leaf coloration (unusual hue – highly characteristic!)',
      'Wilting of new leaves DESPITE moist substrate',
      'Twisted, downward-curling young leaves',
      'Delayed flowering / slow ripening',
      'In severe cases: necrosis of leaf tips on young leaves',
    ],
    causes: [
      'High organic content in the substrate (strongly binds Cu)',
      'pH >7.0',
      'Phosphorus/zinc/iron excess blocks Cu',
      'Peat-based substrates (peat binds Cu extremely)',
    ],
    treatment: [
      'Correct pH to 5.8–6.5',
      'Use Cu-EDTA chelate as a safe option',
      'Copper sulfate very diluted (0.1–0.2 g/L) – USE CAUTION',
      'Reduce P/Zn/Fe if antagonism is suspected',
      'In organic substrates: prefer foliar application',
    ],
    prevention: [
      'Balanced micronutrient supply',
      'In highly organic substrates: use chelated forms',
      'Do not let pH rise above 7.0',
    ],
  },
  'n-molybdaen': {
    name: 'Molybdenum Deficiency (Mo)',
    categoryLabel: 'Nutrient Deficiency',
    symptoms: [
      'Interveinal chlorosis on MIDDLE leaves (unique position!)',
      'Upward leaf margin curling ("cupping")',
      'N-deficiency-like secondary symptoms (Mo is needed for nitrate reductase)',
      '"Whiptail" in severe cases – whip-like deformed leaves',
      'Yellowing spreads from the middle both upward AND downward',
    ],
    causes: [
      'pH too LOW (<5.5) – OPPOSITE of other micronutrients!',
      'Sulfate excess blocks Mo uptake',
      'Acidic substrates without liming',
      'Excess manganese or iron',
    ],
    treatment: [
      'RAISE pH to 6.0–6.5 (opposite of almost all other micro deficiencies!)',
      'Sodium molybdate or ammonium molybdate (0.02–0.05 g/L – tiny amount!)',
      'Lime the substrate',
      'Reduce sulfate supplementation',
      'Foliar spray with Mo solution for rapid effect',
    ],
    prevention: [
      'Do not let pH drop below 5.5',
      'Avoid sulfur over-fertilization',
      'For acidic substrates: work in dolomite lime',
    ],
  },

  // ── Nutrient Excess ─────────────────────────────────────────
  'ue-naehrstoffbrand': {
    name: 'Nutrient Burn (Over-fertilization)',
    categoryLabel: 'Nutrient Excess',
    symptoms: [
      'Brown, crispy leaf tips (starts at 1–3mm, grows inward)',
      'ALL leaves equally affected (not just top or bottom)',
      'Sharp boundary line between healthy and burned tissue',
      'Leaf tips curl downward',
      'In severe burn: brown edges spread across entire leaf',
    ],
    causes: [
      'EC too high – over-fertilized',
      'Salt buildup in substrate over time',
      'Multiple fertilizer products combined without EC measurement',
      '"Hot soil" – pre-fertilized substrate + additional fertilizer',
    ],
    treatment: [
      'FLUSH: Rinse with 3x pot volume of pH-corrected water',
      'Measure runoff EC (goal: runoff EC close to input EC)',
      'Stop feeding for 1 week, then restart at 50% strength',
      'Gradually increase EC to target level',
      'Damaged leaf tips will NOT recover – monitor new growth',
    ],
    prevention: [
      'ALWAYS measure EC before watering',
      'Less is more with fertilization',
      'Monitor runoff EC regularly (>20% above input = flush needed)',
      'Adjust fertilizer strength to growth phase',
    ],
  },
  'ue-stickstoff': {
    name: 'Nitrogen Excess (N Toxicity)',
    categoryLabel: 'Nutrient Excess',
    symptoms: [
      'Toxic dark green leaves (almost unnaturally dark, glossy)',
      '"The Claw" – leaf tips claw DOWNWARD (not taco upward!)',
      'Shiny, waxy leaf surface',
      'Weak, thin stems despite lush foliage',
      'In flower: leafy/airy buds, delayed ripening',
    ],
    causes: [
      'Over-fertilization with nitrogen',
      'Continuing veg fertilizer (N-heavy) into flower',
      '"Hot soil" – heavily pre-fertilized substrate',
      'Organic N release during temperature increase',
    ],
    treatment: [
      'Reduce or stop fertilizer immediately',
      'Flush with pH-corrected water',
      'Switch to bloom fertilizer (low-N, high-PK)',
      'Increase potassium (K partially antagonizes N uptake)',
      'Especially critical in flower – act immediately!',
    ],
    prevention: [
      'Switch to bloom fertilizer in time (by week 2 of flower at the latest)',
      'Measure EC and monitor nitrogen levels',
      'With pre-fertilized substrate: water only for the first 2–4 weeks',
    ],
  },

  // ── Pests ────────────────────────────────────────────────
  's-weisse-fliegen': {
    name: 'Whiteflies',
    categoryLabel: 'Pests',
    symptoms: [
      'Small white insects (1–2mm) fly up when the plant is disturbed',
      'Colonies on leaf undersides – tiny white "moths"',
      'Sticky honeydew on leaves (shiny, sticky)',
      'Yellowish dots/stippling on leaf tops',
      'Sooty mold (black coating) on the honeydew',
    ],
    causes: [
      'Introduced via infested plants or contaminated substrate',
      'Warm temperatures (prefer >20°C)',
      'Poor ventilation and hygiene',
      'Lack of natural predators in indoor grows',
    ],
    treatment: [
      'Hang yellow sticky traps – whiteflies are strongly attracted to yellow',
      'Spray leaf undersides with insecticidal soap or neem oil (every 3 days)',
      'Introduce parasitic wasps (Encarsia formosa) as biological control',
      'Remove heavily infested leaves',
      'For severe infestations: pyrethrum spray as a last resort',
    ],
    prevention: [
      'Hang yellow sticky traps preventatively',
      'Install fine mesh filters on air intakes',
      'Quarantine new plants and clones',
      'Regularly inspect leaf undersides',
    ],
  },
  's-spinnmilben': {
    name: 'Spider Mites',
    categoryLabel: 'Pests',
    symptoms: [
      'Tiny light dots (stippling) on the leaf surface',
      'Fine webbing on leaf undersides and shoot tips',
      'Yellow or bronze discoloration',
      'In severe infestations: leaves dry out and fall off',
    ],
    causes: [
      'Dry, hot environment (above 27°C, below 40% humidity)',
      'Introduced via plants or clones',
      'Poor hygiene in the grow room',
      'Weak, stressed plants are more susceptible',
    ],
    treatment: [
      'Spray leaf undersides with neem oil solution (every 3 days)',
      'Introduce predatory mites (Phytoseiulus persimilis) as biological control',
      'Lower temperature and raise humidity to 50–60%',
      'Remove heavily infested leaves and dispose of them',
      'For severe infestations: use insecticidal soap or pyrethrum',
    ],
    prevention: [
      'Keep humidity above 50%',
      'Keep temperature below 28°C',
      'Quarantine new plants',
      'Regularly inspect leaf undersides',
      'Ensure good air circulation',
    ],
  },
  's-trauermuecken': {
    name: 'Fungus Gnats',
    categoryLabel: 'Pests',
    symptoms: [
      'Small black flies on the substrate and around the plant',
      'Larvae (white, translucent) in the top substrate layers',
      'Slowed growth',
      'Wilting seedlings or young plants',
    ],
    causes: [
      'Constantly moist substrate surface',
      'Organic material in the soil',
      'Overwatering',
      'Infested substrate or introduced flies',
    ],
    treatment: [
      'Let the substrate surface dry out between waterings',
      'Place yellow sticky traps to catch adult flies',
      'Drench substrate with nematodes (Steinernema feltiae)',
      'Use BTI (Bacillus thuringiensis israelensis) as a soil drench',
      'Apply a top layer of quartz sand or perlite',
    ],
    prevention: [
      'Do not overwater – let the surface dry between waterings',
      'Cover substrate surface with sand or perlite',
      'Place yellow sticky traps preventatively',
      'Inspect new soil before use',
    ],
  },
  's-blattlaeuse': {
    name: 'Aphids',
    categoryLabel: 'Pests',
    symptoms: [
      'Colonies of small green, black, or white insects',
      'Prefer shoot tips and leaf undersides',
      'Sticky honeydew on leaves',
      'Deformed new growth',
      'Sooty mold on the honeydew (black coating)',
    ],
    causes: [
      'Introduced via plants or clones',
      'Over-fertilization with nitrogen (soft tissue)',
      'Open windows or unfiltered air intake',
      'Lack of natural predators',
    ],
    treatment: [
      'Cut off heavily infested shoots',
      'Spray with insecticidal soap or neem oil',
      'Introduce ladybugs or lacewing larvae as biological control',
      'Gently rinse the plant with water',
      'For severe infestations: use a pyrethrum-based product',
    ],
    prevention: [
      'Filter air intake',
      'Do not over-fertilize with nitrogen',
      'Quarantine new plants',
      'Regularly inspect shoot tips',
    ],
  },
  's-thripse': {
    name: 'Thrips',
    categoryLabel: 'Pests',
    symptoms: [
      'Silvery/bronze streaks on leaves',
      'Small dark fecal spots on leaf surfaces',
      'Deformed leaves and flowers',
      'Tiny, elongated insects (1–2 mm)',
    ],
    causes: [
      'Introduced via plants',
      'Dry, warm conditions',
      'Poor hygiene',
      'Weeds near the grow area',
    ],
    treatment: [
      'Hang blue sticky traps (thrips prefer blue)',
      'Introduce predatory mites (Amblyseius cucumeris)',
      'Spray neem oil or spinosad-based products',
      'Remove infested leaves',
      'Treat substrate surface (pupae live there)',
    ],
    prevention: [
      'Hang blue sticky traps preventatively',
      'Keep humidity above 50%',
      'Quarantine new plants',
      'Maintain a clean grow room',
    ],
  },

  // ── Diseases ───────────────────────────────────────────────
  'k-mehltau': {
    name: 'Powdery Mildew',
    categoryLabel: 'Diseases',
    symptoms: [
      'White, powdery coating on leaf surfaces',
      'Affected leaves turn yellow and die off',
      'Often starts on older, inner leaves',
      'Can spread to stems and flowers',
    ],
    causes: [
      'High humidity (above 60%) with poor ventilation',
      'Insufficient air circulation',
      'Temperature fluctuations (day/night)',
      'Dense planting without defoliation',
    ],
    treatment: [
      'Remove affected leaves immediately and dispose of them',
      'Spray potassium bicarbonate solution (1 tsp/liter + drop of soap)',
      'Milk-water mixture (1:9) as foliar spray',
      'Significantly improve air circulation',
      'Lower humidity to below 50%',
    ],
    prevention: [
      'Ensure good air circulation with fans',
      'Keep humidity below 55%',
      'Regularly defoliate the plant (lollipop/defoliation)',
      'Maintain spacing between plants',
    ],
  },
  'k-wurzelfaeule': {
    name: 'Root Rot',
    categoryLabel: 'Diseases',
    symptoms: [
      'Brown, mushy roots (instead of white/cream-colored)',
      'Foul smell from the root zone',
      'Plant wilts despite moist substrate',
      'Slowed growth, yellowish leaves',
    ],
    causes: [
      'Overwatering / waterlogging',
      'Poor drainage',
      'Water temperature too high (above 24°C in hydro)',
      'Pythium or Fusarium fungi',
    ],
    treatment: [
      'Reduce watering immediately',
      'Carefully trim affected roots',
      'Dip roots in hydrogen peroxide solution (3%, 1:4 with water)',
      'Repot in fresh, sterile substrate',
      'Use enzyme or mycorrhiza products',
    ],
    prevention: [
      'Let substrate dry well between waterings',
      'Ensure good drainage (perlite, clay pebbles)',
      'Keep water temperature below 22°C in hydro',
      'Use clean pots and sterile substrate',
    ],
  },
  'k-botrytis': {
    name: 'Botrytis (Gray Mold / Bud Rot)',
    categoryLabel: 'Diseases',
    symptoms: [
      'Gray, fuzzy mold on flowers',
      'Brown, dying spots inside buds',
      'Leaves near the flowers turn yellow and wilt',
      'Affected buds feel mushy',
    ],
    causes: [
      'High humidity (above 60%) during flowering',
      'Poor air circulation',
      'Dense, compact bud structure',
      'Injuries to plant material',
    ],
    treatment: [
      'Cut out affected buds immediately with generous margins',
      'Lower humidity to below 45%',
      'Strong air circulation around the plants',
      'Keep temperature stable, avoid fluctuations',
      'Stop spraying over the plants',
    ],
    prevention: [
      'Keep humidity below 50% during flowering',
      'Use fans for air movement',
      'Defoliate to improve airflow',
      'Avoid injuries, use clean tools',
    ],
  },
  'k-septoria': {
    name: 'Septoria (Leaf Spot Disease)',
    categoryLabel: 'Diseases',
    symptoms: [
      'Brown/yellow round spots with dark borders',
      'Starts on the lower leaves',
      'Spots may contain small black dots (fruiting bodies)',
      'Affected leaves dry out and fall off',
    ],
    causes: [
      'High humidity and moisture on leaves',
      'Poor air circulation',
      'Spores in the soil or from infected plants',
      'Warm, humid conditions (20–25°C)',
    ],
    treatment: [
      'Remove affected leaves immediately and dispose of them',
      'Do not water from above, keep leaves dry',
      'Copper-based fungicide as foliar spray (veg phase only)',
      'Neem oil solution as a natural alternative',
      'Improve air circulation',
    ],
    prevention: [
      'Remove lower leaves that touch the soil',
      'Ensure good air circulation',
      'Do not wet leaves when watering',
      'Use clean substrate and maintain grow room hygiene',
    ],
  },

  // ── Environmental Issues ────────────────────────────────────────────
  'u-hitzestress': {
    name: 'Heat Stress',
    categoryLabel: 'Environmental Issues',
    symptoms: [
      'Leaves curl upward (taco shape)',
      'Brown, dry leaf edges',
      'Leaves feel dry and papery',
      'Excessive stretching (in young plants)',
      'Fox-tailing on buds (abnormal growth)',
    ],
    causes: [
      'Temperature above 30°C',
      'Light too close to the plants',
      'Poor ventilation / exhaust',
      'Insufficient cooling in the grow room',
    ],
    treatment: [
      'Lower temperature to 22–28°C',
      'Increase light distance',
      'Boost exhaust or use air conditioning',
      'Shift light cycle to nighttime (light during cooler hours)',
      'Silica supplement can increase heat resistance',
    ],
    prevention: [
      'Monitor temperature continuously (min/max thermometer)',
      'Maintain light distance per manufacturer specifications',
      'Install adequate exhaust and intake ventilation',
      'Plan for air conditioning during hot summer months',
    ],
  },
  'u-lichtbrand': {
    name: 'Light Burn',
    categoryLabel: 'Environmental Issues',
    symptoms: [
      'Bleaching/whitening of the TOPMOST leaves (closest to the light)',
      'Follows the LIGHT PATTERN, not the plant structure – key to identification!',
      'Leaves become papery/crispy',
      'With LEDs: can occur even at LOW temperatures!',
      'Buds can bleach unnaturally white – looks "cool" but is damage',
    ],
    causes: [
      'Light too close to the plants',
      'PPFD >1000 umol/m2/s is too much for most strains',
      'With LEDs: heat and light are NOT correlated – always check PPFD/DLI!',
      'Sudden increase in light intensity or transplanting closer to light',
    ],
    treatment: [
      'Increase light distance immediately (at least 5–10 cm more)',
      'Reduce LED dimmer (if available)',
      'Measure PAR/PPFD – target: 600–900 umol/m2/s',
      'Bleached leaves will NOT recover – remove if dead',
    ],
    prevention: [
      'Use a PPFD meter – do not go by temperature alone (especially with LEDs!)',
      'Follow manufacturer recommendations for light distance',
      'Increase light intensity gradually',
      'Readjust light distance after the stretch',
    ],
  },
  'u-ueberwaesserung': {
    name: 'Overwatering',
    categoryLabel: 'Environmental Issues',
    symptoms: [
      'Leaves droop limply (drooping)',
      'Leaves feel firm and puffy',
      'Yellowish discoloration',
      'Pot feels heavy',
      'Slow growth',
    ],
    causes: [
      'Watering too frequently',
      'Poor drainage in the pot',
      'Pot too large for the plant',
      'Compacted substrate without perlite/clay pebbles',
    ],
    treatment: [
      'Stop watering immediately until the substrate has dried out',
      'Lift the pot – only water again when it feels light',
      'Check drainage and improve if necessary',
      'For compacted substrate: carefully mix in perlite or repot',
    ],
    prevention: [
      'Lift test: pick up the pot to assess moisture',
      'Finger test: only water when the top 2–3 cm are dry',
      'Use drainage holes and saucers',
      'Mix perlite or clay pebbles into substrate (20–30%)',
    ],
  },
  'u-unterwaesserung': {
    name: 'Underwatering',
    categoryLabel: 'Environmental Issues',
    symptoms: [
      'Leaves droop limply and feel thin',
      'Leaves feel dry and papery',
      'Substrate is completely dry and pulls away from the pot edges',
      'Pot feels very light',
      'Plant recovers quickly after watering',
    ],
    causes: [
      'Watering too infrequently',
      'Pot too small for the plant',
      'High temperatures increase water consumption',
      'Hydrophobic substrate (dry coco or peat)',
    ],
    treatment: [
      'Water slowly and thoroughly until water runs from the drainage hole',
      'For hydrophobic substrate: place pot in water and let it soak from below',
      'Add a few drops of wetting agent to the water',
      'Plant should recover within hours',
    ],
    prevention: [
      'Establish a regular watering schedule',
      'Choose the right pot size',
      'A mulch layer on the substrate can reduce evaporation',
      'Check more frequently during heat',
    ],
  },
  'u-windburn': {
    name: 'Wind Burn (Wind Stress)',
    categoryLabel: 'Environmental Issues',
    symptoms: [
      'Clawing/curling ONLY ON ONE SIDE of the plant (ASYMMETRIC!)',
      'Thickened stems on the wind-facing side',
      'Dry, crispy leaf edges only on the affected side',
      'Opposite side looks completely normal',
      'Possible growth delay on the wind-facing side',
    ],
    causes: [
      'Fan too strong and/or too close to the plant',
      'Fan not oscillating (constant wind on one spot)',
      'Air intake directed straight at the plant',
      'Young plants/seedlings are especially sensitive',
    ],
    treatment: [
      'Move the fan further away or reduce the speed setting',
      'Turn on oscillation (fan must sweep)',
      'Indirect air circulation: point fan at a wall',
      'Mildly damaged leaves usually recover on their own',
      'For severe damage: remove affected leaves',
    ],
    prevention: [
      'ALWAYS set the fan to oscillate',
      'Minimum distance of 30–50 cm to the nearest plant',
      'Gentle, indirect breeze instead of strong direct wind',
      'Tip: Asymmetry distinguishes from N toxicity (symmetric) and heat stress (taco upward)',
    ],
  },
  'u-kaeltestress': {
    name: 'Cold Stress',
    categoryLabel: 'Environmental Issues',
    symptoms: [
      'Purple discoloration of stems and petioles',
      'Slowed growth, plant looks "frozen"',
      'Leaves curl downward, become stiff',
      'Phosphorus deficiency symptoms despite adequate P in the substrate',
      'Roots absorb nutrients poorly (especially P below 15°C)',
    ],
    causes: [
      'Night temperature below 15°C',
      'Cold floor/substrate (placed directly on cold surface)',
      'Air intake directly from outside without preheating',
      'Air conditioning too strong or incorrectly set',
    ],
    treatment: [
      'Raise temperature to at least 18°C (day 22–28°C, night >18°C)',
      'Place heat mat under pots for root zone >20°C',
      'Preheat intake air or introduce it indirectly',
      'Do not water with cold water – water temperature 18–22°C',
      'Purple discoloration recovers after temperature correction',
    ],
    prevention: [
      'Use a min/max thermometer with night temperature logging',
      'Do not place pots directly on cold concrete/tiles (use styrofoam underneath)',
      'Temperature difference day/night max 8–10°C',
      'Monitor VPD – cold air holds less moisture',
    ],
  },
  'u-rootbound': {
    name: 'Root Bound',
    categoryLabel: 'Environmental Issues',
    symptoms: [
      'Roots growing out of drainage holes',
      'Water runs straight through without being absorbed by the substrate',
      'Plant wilts quickly after watering (needs daily watering)',
      'Growth stall despite adequate fertilization',
      'Plant tips over easily, plant-to-pot ratio looks disproportionate',
    ],
    causes: [
      'Pot too small for the plant size',
      'Staying too long in the same pot',
      'Fast-growing genetics in a small container',
    ],
    treatment: [
      'Transplant to a 2–3x larger pot with fresh substrate',
      'Gently loosen the root ball – slightly tear matted outer roots',
      'After transplanting, water only for 1–2 days (no fertilizer)',
      'Do not transplant during flower – flush and water more frequently instead',
    ],
    prevention: [
      'Choose the right pot size from the start: 11–15L for standard indoor plants',
      'Air pots or fabric pots prevent root circling (air pruning)',
      'Transplant at the latest when roots become visible at the bottom',
      'In coco: fertigate more frequently instead of transplanting (3–5x daily in flower)',
    ],
  },
  'u-ph-probleme': {
    name: 'pH Problems',
    categoryLabel: 'Environmental Issues',
    symptoms: [
      'Multiple deficiency symptoms appearing at the same time (lockout)',
      'Patchy discoloration across various leaves',
      'Growth stall despite adequate fertilization',
      'Mixed brown spots, yellowing, and necrosis',
    ],
    causes: [
      'pH of the irrigation water not properly adjusted',
      'pH drift in the substrate over time',
      'Salt buildup in substrate shifts pH',
      'Wrong pH target for the substrate type used',
    ],
    treatment: [
      'Measure and correct the pH of irrigation water',
      'Soil: pH 6.0–7.0, Coco/Hydro: pH 5.5–6.5',
      'Flush the substrate with correctly pH-adjusted water',
      'After flushing, water with fresh pH-corrected nutrient solution',
    ],
    prevention: [
      'Measure pH with every watering',
      'Calibrate pH meter regularly',
      'Monitor EC/PPM to detect salt buildup',
      'Measure runoff pH and EC to check substrate conditions',
    ],
  },
  'u-hermaphrodit': {
    name: 'Hermaphrodite (Intersex)',
    categoryLabel: 'Environmental Issues',
    symptoms: [
      'Yellow "bananas" (stamens) protruding from buds',
      'Small round pollen sacs at leaf nodes between buds',
      'Seeds in the flowers (small green/brown balls)',
      'Mix of female pistils and male pollen sacs',
      'Pollen sacs: round, smooth balls on short stems, often in clusters',
    ],
    causes: [
      'Light stress: light leak during dark period (most common cause!)',
      'Extreme heat stress (>35°C) or light burn',
      'Severely stressed plant (over-/underwatering, severe nutrient deficiency)',
      'Genetic predisposition (unstable genetics, poorly bred seeds)',
      'Harvesting too late – plant tries to self-pollinate',
    ],
    treatment: [
      'Individual bananas: carefully remove with tweezers, continue monitoring the plant',
      'Few pollen sacs: check daily and remove, address the stress factor',
      'Many pollen sacs: remove the plant immediately to prevent pollination of other plants',
      'For bananas in late flower: consider harvesting immediately',
      'NEVER leave a heavily hermied plant among female plants!',
    ],
    prevention: [
      'Dark period must be 100% light-tight – NO light leaks (key to prevention!)',
      'Keep temperature below 30°C, avoid heat spikes',
      'Minimize stress factors – maintain consistent conditions during flowering',
      'Use quality seeds from reputable breeders',
      'Check timers – interruption of the dark period is the most common cause',
    ],
  },
  'u-erntezeitpunkt': {
    name: 'Harvest Timing (Trichomes)',
    categoryLabel: 'Environmental Issues',
    symptoms: [
      'Trichomes clear/glassy = NOT yet ripe, THC production still ongoing',
      'Trichomes milky/white = PEAK potency – maximum THC, CBD, and terpenes',
      'Trichomes amber/gold = THC converting to CBN – more couch-lock/body effect',
      'Over 20% amber trichomes = increasingly sedating/sleepy effect',
      'Pistil method: 70–80% brown/curled pistils = harvest window is open',
    ],
    causes: [
      'Harvesting too early: Most common beginner mistake! Result = weak, hay-smelling buds',
      'Harvesting too late: THC degradation, potency drops, more sedation',
      'Sativa strains: trichomes may never turn amber – harvest when milky!',
      'Fox-tailing from heat stress produces new white pistils – do NOT interpret as "unripe"!',
    ],
    treatment: [
      'Use a USB microscope (60–100x) or jeweler\'s loupe – trichomes cannot be judged by the naked eye',
      'Check trichomes on BUDS, NOT on sugar leaves (sugar leaves ripen faster)',
      'For stronger effect: harvest when mostly milky trichomes (0–10% amber)',
      'For relaxing effect: harvest at 20–30% amber trichomes',
      'If bud rot, hermie bananas, or dying leaves appear: HARVEST IMMEDIATELY!',
    ],
    prevention: [
      'Start checking trichomes daily from week 6 of flowering',
      'The harvest window is approximately 1–2 weeks long – slightly late is better than too early',
      'Purple trichomes on some strains are NORMAL and say nothing about ripeness',
      'Ignore foxtails – only use the main buds for ripeness assessment',
    ],
  },
};
