export type LibraryCategory = 'naehrstoffmangel' | 'naehrstoffueberschuss' | 'schaedlinge' | 'krankheiten' | 'umweltprobleme';
export type LibrarySeverity = 'niedrig' | 'mittel' | 'hoch' | 'kritisch';

export interface LibraryEntry {
  id: string;
  name: string;
  category: LibraryCategory;
  categoryLabel: string;
  emoji: string;
  symptoms: string[];
  causes: string[];
  treatment: string[];
  prevention: string[];
  severity: LibrarySeverity;
}

export const categoryLabels: Record<LibraryCategory, string> = {
  naehrstoffmangel: 'Nährstoffmangel',
  naehrstoffueberschuss: 'Nährstoffüberschuss',
  schaedlinge: 'Schädlinge',
  krankheiten: 'Krankheiten',
  umweltprobleme: 'Umweltprobleme',
};

export const categoryColors: Record<LibraryCategory, string> = {
  naehrstoffmangel: '#FBBF24',
  naehrstoffueberschuss: '#FB923C',
  schaedlinge: '#F87171',
  krankheiten: '#A78BFA',
  umweltprobleme: '#38BDF8',
};

export const severityColors: Record<LibrarySeverity, string> = {
  niedrig: '#4ADE80',
  mittel: '#FBBF24',
  hoch: '#FB923C',
  kritisch: '#F87171',
};

export const libraryEntries: LibraryEntry[] = [
  // ── Nährstoffmangel ──────────────────────────────────────────
  {
    id: 'n-stickstoff',
    name: 'Stickstoffmangel (N)',
    category: 'naehrstoffmangel',
    categoryLabel: 'Nährstoffmangel',
    emoji: '🍂',
    symptoms: [
      'Gleichmäßige Vergilbung UNTERER/ALTER Blätter (gesamtes Blatt inkl. Adern)',
      'Blätter werden weich/schlaff, fallen ab – Pflanze wird "skelettartig" unten',
      'Gesamte Pflanze hellgrün, langsames Wachstum',
      'Stängel können rötlich werden',
      'Häufigster Mangel! Biomasse-Verlust bis 50% möglich (Cockson et al. 2019)',
    ],
    causes: [
      'EC/Düngermenge zu niedrig – häufigste Ursache',
      'pH-Wert außerhalb des optimalen Bereichs (Erde 6.0–7.0, Kokos 5.8–6.2)',
      'Ausgelaugtes Substrat, übermäßiges Flushen',
      'Wurzelprobleme (Überwässerung, Wurzelfäule)',
    ],
    treatment: [
      'EC auf Herstellerempfehlung erhöhen',
      'Schnelle Soforthilfe: Blattspray mit Harnstoff 0.5%',
      'pH-Wert auf 6.0–6.5 (Erde) bzw. 5.8–6.0 (Kokos) korrigieren',
      'Stark vergilbte Blätter entfernen, leicht betroffene lassen',
    ],
    prevention: [
      'EC regelmäßig messen und Düngeplan einhalten',
      'pH-Wert bei jeder Bewässerung kontrollieren',
      'In Blüte: N reduzieren, aber NICHT eliminieren',
      'Leichte Vergilbung in den letzten 2 Wochen Blüte ist NORMAL (Seneszenz)',
    ],
    severity: 'mittel',
  },
  {
    id: 'n-phosphor',
    name: 'Phosphormangel (P)',
    category: 'naehrstoffmangel',
    categoryLabel: 'Nährstoffmangel',
    emoji: '🍆',
    symptoms: [
      'Dunkelgrüne bis blau-grüne, MATTE/stumpfe Blätter (Glanz geht verloren!)',
      'Olive-grüne, eingesunken wirkende Flecken auf alten Blättern (Frühstadium)',
      'Violette/purpur Stängel und Blattstiele (fortgeschrittenes Stadium)',
      'Untere Blätter werden bronze/braun und fallen ab',
      'Schlechte Blüten-/Wurzelentwicklung, kleine Buds',
    ],
    causes: [
      'pH außerhalb des schmalen Optimalbereichs (P hat engen Bereich!)',
      'Kalte Temperaturen <15°C blockieren P-Aufnahme massiv',
      'Fe/Zn-Überschuss blockiert Phosphor',
      'Zu wenig Phosphor im Dünger (besonders in der Blüte)',
    ],
    treatment: [
      'pH-Wert auf 6.0–6.5 (Erde) korrigieren',
      'Mono-Kaliumphosphat oder Blüte-Booster geben',
      'Wurzelzone warm halten (>18°C)',
      'Mykorrhiza-Pilze verbessern P-Aufnahme um bis zu 30%',
      'Tipp: Genetisch violette Stängel sind GLÄNZEND – P-Mangel ist MATT',
    ],
    prevention: [
      'Temperatur >18°C am Wurzelbereich sicherstellen',
      'pH stabil halten – P hat den engsten Verfügbarkeitsbereich aller Makros',
      'In der Blüte Blüte-Dünger mit ausreichend P verwenden',
      'Nicht übermäßig Fe/Zn supplementieren',
    ],
    severity: 'hoch',
  },
  {
    id: 'n-kalium',
    name: 'Kaliummangel (K)',
    category: 'naehrstoffmangel',
    categoryLabel: 'Nährstoffmangel',
    emoji: '🍁',
    symptoms: [
      'Rostbraune Randnekrose an unteren/alten Blättern – beginnt am Sägezahnrand',
      'Ränder zuerst GELB, dann BRAUN/knusprig/tot (trockenes, papierartiges Gewebe)',
      'Von unten nach oben fortschreitend, ganzer Blattrand betroffen',
      'Schwache/brüchige Stängel, erhöhte Krankheitsanfälligkeit',
      'UNTERSCHIED zu Nährstoffbrand: K = ganzer Rand, Burn = nur Spitzen 1–3mm!',
    ],
    causes: [
      'K-Bedarf steigt in der Blüte MASSIV – häufigster Mangel in der Blüte!',
      'Ca/Mg-Überschuss blockiert K-Aufnahme (Antagonismus)',
      'pH-Wert außerhalb des optimalen Bereichs',
      'Überwässerung oder ausgelaugtes Substrat',
    ],
    treatment: [
      'Kaliumsulfat oder K-betonten Blüte-Dünger verwenden',
      'pH-Wert auf 6.0–6.5 (Erde) korrigieren',
      'Ca/Mg-Gabe vorübergehend reduzieren',
      'Run-off EC testen – ggf. Flush + neuer Nährstoff-Ansatz',
    ],
    prevention: [
      'In der Blüte Blüte-Dünger mit hohem K-Anteil verwenden',
      'EC und Run-off regelmäßig messen',
      'Nährstoff-Antagonismus beachten: zu viel Ca/Mg hemmt K',
      'Substrat nicht auslaugen durch übermäßiges Flushen',
    ],
    severity: 'hoch',
  },
  {
    id: 'n-kalzium',
    name: 'Kalziummangel (Ca)',
    category: 'naehrstoffmangel',
    categoryLabel: 'Nährstoffmangel',
    emoji: '🟤',
    symptoms: [
      'Zufällig verteilte braune/schwarze Flecken auf NEUEN Blättern (immobil!)',
      'Deformierter Neuwuchs – schmaler an der Basis, gekräuselt',
      'Brüchige Stängel, Blattspitzen hakeln sich',
      'Tod der Wachstumsspitze bei schwerem Mangel → vermehrte Seitentriebe',
      'In Kokos: PFLICHT CalMag zu supplementieren!',
    ],
    causes: [
      'pH zu niedrig (<6.0 in Erde) – Ca wird bei saurem pH schlecht aufgenommen',
      'Kokos-Substrat bindet Ca an Kationenaustauschplätze',
      'RO-Wasser ohne CalMag-Zusatz',
      'K/Mg-Überschuss blockiert Ca (Antagonismus)',
    ],
    treatment: [
      'CalMag-Zusatz vom gleichen Hersteller wie Hauptdünger verwenden',
      'pH-Wert auf 6.2–6.5 (Erde) anheben',
      'Luftfeuchtigkeit auf 40–60% – fördert Transpiration und Ca-Transport',
      'Gute Luftzirkulation sicherstellen',
    ],
    prevention: [
      'In Kokos: IMMER CalMag supplementieren',
      'Bei RO-Wasser: CalMag ist Pflicht',
      'pH-Wert stabil >6.0 halten',
      'K/Mg nicht überdosieren – Ca-Aufnahme wird gehemmt',
    ],
    severity: 'hoch',
  },
  {
    id: 'n-magnesium',
    name: 'Magnesiummangel (Mg)',
    category: 'naehrstoffmangel',
    categoryLabel: 'Nährstoffmangel',
    emoji: '💛',
    symptoms: [
      'Intervenale Chlorose an UNTEREN/ALTEN Blättern – "Skelettmuster" (Adern SATT grün, dazwischen gelb)',
      'STARKER Kontrast zwischen grünen Adern und gelbem Gewebe ("Fischgräten-Muster")',
      'Ränder können rötlich/violett werden, rostige Flecken im Verlauf',
      'Häufig in der Blüte und bei Kokos-Substrat',
      'ACHTUNG: Leicht grünere Adern bei sonst gelbem Blatt = eher N-Mangel, NICHT Mg!',
    ],
    causes: [
      'pH zu niedrig (<5.8 in Kokos, <6.0 in Erde) – Mg-Lockout',
      'K-Überschuss hemmt Mg-Aufnahme (K-Mg-Antagonismus – sehr häufig!)',
      'Kokos-Substrat bindet Mg',
      'Kalkarmes/weiches Wasser oder RO-Wasser',
    ],
    treatment: [
      'Bittersalz (Epsom Salt) 1–2 g/L als Bewässerung',
      'CalMag-Zusatz vom gleichen Hersteller verwenden',
      'Blattspray mit Bittersalz (1 TL/Liter) als Soforthilfe',
      'pH-Wert auf 6.0–6.5 korrigieren',
      'K-Dosierung prüfen und ggf. reduzieren',
    ],
    prevention: [
      'CalMag bei Kokos und RO-Wasser IMMER verwenden',
      'pH nicht unter 5.8 (Kokos) bzw. 6.0 (Erde) fallen lassen',
      'K nicht überdosieren – häufigster Auslöser von Mg-Mangel',
      'Substrattemperatur über 18°C halten',
    ],
    severity: 'mittel',
  },
  {
    id: 'n-eisen',
    name: 'Eisenmangel (Fe)',
    category: 'naehrstoffmangel',
    categoryLabel: 'Nährstoffmangel',
    emoji: '🌿',
    symptoms: [
      'Intervenale Chlorose an NEUEN/OBEREN Blättern – scharfes grünes Adernetz auf gelbem Grund',
      'Bei schwerem Mangel: Blätter werden fast WEISS/gebleicht',
      'Betrifft NUR neue Blätter (immobil!) – DAS unterscheidet von Mg-Mangel',
      'Neuwuchs schwach, Triebspitzen verlangsamt',
      'Echter Fe-Mangel ist SELTEN – meist ist es pH-Lockout (pH >6.5)!',
    ],
    causes: [
      'pH zu hoch (>6.5) – häufigste Ursache! Fe wird bei hohem pH blockiert',
      'Mn/Zn/Cu-Überschuss oder P-Überschuss blockiert Fe',
      'Überwässerung / schlechte Drainage',
      'Kalkhaltiges Wasser oder kalkige Substrate',
    ],
    treatment: [
      'pH auf 5.8–6.5 senken – oft reicht das allein!',
      'Fe-EDDHA-Chelat (stabil bis pH 9, beste Wahl bei hohem pH)',
      'Blattspray: Fe-EDTA für schnelle Aufnahme',
      'Drainage verbessern, P-Gabe reduzieren falls Antagonismus',
    ],
    prevention: [
      'pH stabil bei 5.8–6.5 halten – wichtigste Maßnahme',
      'Chelat-basierte Dünger verwenden (EDDHA > DTPA > EDTA)',
      'Nicht überwässern, gute Drainage sicherstellen',
      'Kein übermäßiges Kalken des Substrats',
    ],
    severity: 'mittel',
  },

  {
    id: 'n-mangan',
    name: 'Manganmangel (Mn)',
    category: 'naehrstoffmangel',
    categoryLabel: 'Nährstoffmangel',
    emoji: '🟨',
    symptoms: [
      'Intervenale Chlorose an jungen/oberen Blättern (milder als Fe)',
      'Tan/hellbraune Sprenkel auf der Blattfläche ("speckled pattern")',
      'Papierartige, dünne Textur der betroffenen Blätter',
      'Flecken können bei Fortschreiten zusammenfließen',
      'Wachstumsverlangsamung bei schwerem Mangel',
    ],
    causes: [
      'pH zu hoch (>6.5 in Erde, >6.0 in Kokos/Hydro)',
      'Eisen-Überschuss (Fe-Mn-Antagonismus)',
      'Überwässerung / schlechte Drainage (anaerobe Bedingungen)',
      'Kalkhaltige Substrate oder kalkhaltiges Wasser',
    ],
    treatment: [
      'pH senken auf optimalen Bereich (Erde 6.0–6.5, Kokos 5.8–6.0)',
      'Blattspray mit Mangan-Chelat (EDTA) 0.05–0.1%',
      'Bewässerung optimieren – Substrat nicht dauernass halten',
      'Fe-Gaben reduzieren falls Antagonismus vermutet wird',
      'Geduld: Bestehende Schäden erholen sich NICHT, nur Neuwuchs zeigt Besserung',
    ],
    prevention: [
      'pH regelmäßig messen und im optimalen Bereich halten',
      'Ausgewogene Mikronährstoff-Versorgung (kein Nährstoff überdosieren)',
      'Gute Drainage sicherstellen',
      'Leitungswasser auf Karbonathärte prüfen',
    ],
    severity: 'mittel',
  },
  {
    id: 'n-zink',
    name: 'Zinkmangel (Zn)',
    category: 'naehrstoffmangel',
    categoryLabel: 'Nährstoffmangel',
    emoji: '🌱',
    symptoms: [
      'Gestauter Neuwuchs mit winzigen, gebündelten Blättern ("Rosettenbildung")',
      'Stark verkürzte Internodien – Pflanze wirkt gestaucht/zwergwüchsig',
      'Intervenale Chlorose, fleckiger als bei Eisen',
      'Verdrehte, gewellte Blattränder',
      'Bei schwerem Mangel: nekrotische Flecken auf jungen Blättern',
    ],
    causes: [
      'pH zu hoch (>7.0)',
      'Phosphor-Überschuss blockiert Zink (P-Zn-Antagonismus – häufiger Fehler!)',
      'Alkalische/kalkhaltige Substrate',
      'Übermäßige Fe- oder Cu-Zufuhr',
    ],
    treatment: [
      'pH auf 6.0–6.5 (Erde) bzw. 5.8–6.0 (Kokos) korrigieren',
      'Phosphor-Gabe reduzieren falls P-Überschuss vorliegt',
      'Blattspray: Zink-Chelat (EDTA) 0.05–0.1%',
      'Zinksulfat über Bewässerung (0.5–1 g/L)',
      'Neuwuchs beobachten – alte Blätter erholen sich NICHT',
    ],
    prevention: [
      'P-Überdüngung vermeiden (häufiger Fehler in der Blütephase!)',
      'pH-Wert stabil im leicht sauren Bereich halten',
      'Qualitäts-Chelat-Dünger mit allen Mikronährstoffen verwenden',
    ],
    severity: 'mittel',
  },
  {
    id: 'n-schwefel',
    name: 'Schwefelmangel (S)',
    category: 'naehrstoffmangel',
    categoryLabel: 'Nährstoffmangel',
    emoji: '💚',
    symptoms: [
      'Gleichmäßige Vergilbung NEUER/OBERER Blätter – Adern vergilben MIT (kein intervenales Muster!)',
      'Betroffene Blätter bleiben FEST und aufrecht (kein Welken)',
      'Violette Verfärbung der Stängel möglich',
      'Wachstumsverlangsamung, dünne/spröde Stängel',
      'Bei schwerem Mangel: kleine nekrotische Flecken',
    ],
    causes: [
      'pH >7.5 (alkalisch)',
      'Verwendung von RO-Wasser ohne S-Supplementierung',
      'Schwefelarme organische Substrate',
      'Extrem gefiltertes/weiches Wasser',
    ],
    treatment: [
      'pH korrigieren (senken auf 6.0–6.5)',
      'Bittersalz (Magnesiumsulfat/Epsom Salt) 1–2 g/L als Bewässerung',
      'Kaliumsulfat als Alternative',
      'Blattspray mit Bittersalz 0.5 g/L für schnelle Aufnahme',
      'Bei RO-Wasser: Cal-Mag-Produkt mit Schwefel ergänzen',
    ],
    prevention: [
      'Bei RO-Wasser immer schwefelhaltige Additive nutzen',
      'pH nicht über 7.0 steigen lassen',
      'Gypsum (Calciumsulfat) als Substrat-Beimischung erwägen',
    ],
    severity: 'mittel',
  },
  {
    id: 'n-bor',
    name: 'Bormangel (B)',
    category: 'naehrstoffmangel',
    categoryLabel: 'Nährstoffmangel',
    emoji: '🥀',
    symptoms: [
      'Deformierte, verdrehte Triebspitzen',
      'Hohle Stängel (Hohlstängel) – fast einzigartiges Zeichen für Bor!',
      'Raue, dicke, brüchige Blattoberfläche',
      'Brüchige Stiele die leicht abbrechen',
      'Schlechte Blütenentwicklung, lockere Buds',
    ],
    causes: [
      'pH >6.5 (alkalisch)',
      'Überwässerung (Bor wird leicht ausgewaschen)',
      'Calcium-Überschuss (Ca-B-Antagonismus)',
      'Niedrige Luftfeuchtigkeit (<30% RH)',
    ],
    treatment: [
      'pH auf 6.0–6.5 senken',
      'Borsäure-Lösung: SEHR VORSICHTIG, nur 0.25–0.5 g/L (extrem schmale Toleranz!)',
      'Borax als mildere Alternative zu Borsäure',
      'Bewässerung optimieren (weniger, aber gründlicher)',
      'WARNUNG: Überdosierung führt schnell zu Bor-Toxizität!',
    ],
    prevention: [
      'pH stabil im leicht sauren Bereich halten',
      'Nicht übermäßig Calcium supplementieren',
      'Qualitäts-Mikronährstoff-Mix verwenden',
      'Nie "mehr hilft mehr" – extrem schmaler Bereich zwischen Mangel und Toxizität',
    ],
    severity: 'mittel',
  },
  {
    id: 'n-kupfer',
    name: 'Kupfermangel (Cu)',
    category: 'naehrstoffmangel',
    categoryLabel: 'Nährstoffmangel',
    emoji: '🔷',
    symptoms: [
      'Blau-grüne Blattfärbung (ungewöhnlicher Farbton – hochcharakteristisch!)',
      'Welken neuer Blätter TROTZ feuchtem Substrat',
      'Verdrehte, nach unten gerollte junge Blätter',
      'Verzögerte Blüte / langsame Reifung',
      'Bei schwerem Mangel: Nekrose der Blattspitzen junger Blätter',
    ],
    causes: [
      'Hoher organischer Gehalt im Substrat (bindet Cu stark)',
      'pH >7.0',
      'Phosphor/Zink/Eisen-Überschuss blockiert Cu',
      'Torfhaltige Substrate (Torf bindet Cu extrem)',
    ],
    treatment: [
      'pH auf 5.8–6.5 korrigieren',
      'Cu-EDTA-Chelat als sichere Variante verwenden',
      'Kupfersulfat sehr verdünnt (0.1–0.2 g/L) – VORSICHT',
      'P/Zn/Fe-Gabe reduzieren falls Antagonismus vermutet',
      'In organischen Substraten: Blattapplikation bevorzugen',
    ],
    prevention: [
      'Ausgewogene Mikronährstoff-Versorgung',
      'Bei stark organischen Substraten: Chelat-Form verwenden',
      'pH nicht über 7.0 steigen lassen',
    ],
    severity: 'mittel',
  },
  {
    id: 'n-molybdaen',
    name: 'Molybdänmangel (Mo)',
    category: 'naehrstoffmangel',
    categoryLabel: 'Nährstoffmangel',
    emoji: '🔶',
    symptoms: [
      'Intervenale Chlorose an MITTLEREN Blättern (einzigartige Position!)',
      'Blattrand-Aufwärtskrümmung ("cupping")',
      'N-Mangel-ähnliche Begleitsymptome (Mo wird für Nitrat-Reduktase benötigt)',
      '"Whiptail" bei schwerem Mangel – peitschenartig deformierte Blätter',
      'Vergilbung wandert von der Mitte nach oben UND unten',
    ],
    causes: [
      'pH zu NIEDRIG (<5.5) – GEGENSÄTZLICH zu anderen Mikronährstoffen!',
      'Sulfat-Überschuss blockiert Mo-Aufnahme',
      'Saure Substrate ohne Kalkung',
      'Überschuss an Mangan oder Eisen',
    ],
    treatment: [
      'pH ERHÖHEN auf 6.0–6.5 (gegenteilig zu fast allen anderen Mikro-Mängeln!)',
      'Natriummolybdat oder Ammoniummolybdat (0.02–0.05 g/L – winzige Menge!)',
      'Kalkung des Substrats',
      'Sulfat-Gabe reduzieren',
      'Blattspray mit Mo-Lösung für schnelle Wirkung',
    ],
    prevention: [
      'pH nicht unter 5.5 fallen lassen',
      'Schwefel-Überdüngung vermeiden',
      'Bei saurem Substrat: Dolomit-Kalk einarbeiten',
    ],
    severity: 'mittel',
  },

  // ── Nährstoffüberschuss ─────────────────────────────────────────
  {
    id: 'ue-naehrstoffbrand',
    name: 'Nährstoffbrand (Überdüngung)',
    category: 'naehrstoffueberschuss',
    categoryLabel: 'Nährstoffüberschuss',
    emoji: '🔥',
    symptoms: [
      'Braune, knusprige Blattspitzen (beginnt bei 1–3mm, wächst nach innen)',
      'ALLE Blätter gleichmäßig betroffen (nicht nur oben oder unten)',
      'Scharfe Grenzlinie zwischen gesundem und verbranntem Gewebe',
      'Blattspitzen kräuseln sich nach unten',
      'Bei schwerem Burn: braune Ränder breiten sich über ganzes Blatt aus',
    ],
    causes: [
      'EC zu hoch – zu stark gedüngt',
      'Salzaufbau im Substrat über Zeit',
      'Mehrere Dünger-Produkte kombiniert ohne EC-Messung',
      '"Hot Soil" – vorgedüngtes Substrat + zusätzlicher Dünger',
    ],
    treatment: [
      'FLUSH: Durchspülen mit 3x Topfvolumen pH-korrektem Wasser',
      'EC des Ablaufwassers messen (Ziel: Run-off EC nahe Input-EC)',
      'Düngung für 1 Woche aussetzen, dann bei 50% Stärke wieder starten',
      'EC schrittweise auf Zielwert erhöhen',
      'Beschädigte Blattspitzen erholen sich NICHT – Neuwuchs beobachten',
    ],
    prevention: [
      'IMMER EC messen vor dem Gießen',
      'Weniger ist mehr bei der Düngung',
      'Run-off EC regelmäßig kontrollieren (>20% über Input = Flush nötig)',
      'Düngerstärke an Wachstumsphase anpassen',
    ],
    severity: 'hoch',
  },
  {
    id: 'ue-stickstoff',
    name: 'Stickstoff-Überschuss (N-Toxizität)',
    category: 'naehrstoffueberschuss',
    categoryLabel: 'Nährstoffüberschuss',
    emoji: '🦎',
    symptoms: [
      'Toxisch dunkelgrüne Blätter (fast unnatürlich dunkel, glänzend)',
      '"The Claw" – Blattspitzen klauen nach UNTEN (nicht Taco nach oben!)',
      'Glänzende, wachsartige Blattoberfläche',
      'Schwache, dünne Stiele trotz üppigem Blattwerk',
      'In der Blüte: laubige/lockere Buds, verzögerte Reifung',
    ],
    causes: [
      'Überdüngung mit Stickstoff',
      'Wachstumsdünger (N-betont) in Blüte weiterverwenden',
      '"Hot Soil" – stark vorgedüngtes Substrat',
      'Organischer N-Release bei Temperaturanstieg',
    ],
    treatment: [
      'Dünger sofort reduzieren oder aussetzen',
      'Flush mit pH-korrektem Wasser',
      'Auf Blüte-Dünger (niedrig-N, hoch-PK) umstellen',
      'Kalium erhöhen (K antagonisiert N-Aufnahme teilweise)',
      'In Blüte besonders kritisch – sofort handeln!',
    ],
    prevention: [
      'Rechtzeitiger Wechsel auf Blüte-Dünger (spätestens Woche 2 Blüte)',
      'EC messen und Stickstoff-Anteil beachten',
      'Bei vorgedüngtem Substrat: erste 2–4 Wochen nur Wasser',
    ],
    severity: 'hoch',
  },

  // ── Schädlinge ────────────────────────────────────────────────
  {
    id: 's-spinnmilben',
    name: 'Spinnmilben',
    category: 'schaedlinge',
    categoryLabel: 'Schädlinge',
    emoji: '🕷️',
    symptoms: [
      'Winzige helle Punkte (Stippen) auf der Blattoberseite',
      'Feine Spinnweben an Blattunterseiten und Triebspitzen',
      'Gelbe oder bronzefarbene Verfärbungen',
      'Bei starkem Befall: Blätter trocknen aus und fallen ab',
    ],
    causes: [
      'Trockene, heiße Umgebung (über 27°C, unter 40% Luftfeuchtigkeit)',
      'Eingeschleppte Pflanzen oder Klone',
      'Mangelnde Hygiene im Anbauraum',
      'Schwache, gestresste Pflanzen sind anfälliger',
    ],
    treatment: [
      'Blattunterseiten mit Neemöl-Lösung besprühen (alle 3 Tage)',
      'Raubmilben (Phytoseiulus persimilis) als Nützlinge einsetzen',
      'Temperatur senken und Luftfeuchtigkeit auf 50–60% erhöhen',
      'Stark befallene Blätter entfernen und entsorgen',
      'Bei starkem Befall: Kaliseife oder Pyrethrum verwenden',
    ],
    prevention: [
      'Luftfeuchtigkeit über 50% halten',
      'Temperatur unter 28°C halten',
      'Neue Pflanzen in Quarantäne halten',
      'Regelmäßig Blattunterseiten kontrollieren',
      'Gute Luftzirkulation sicherstellen',
    ],
    severity: 'hoch',
  },
  {
    id: 's-trauermuecken',
    name: 'Trauermücken',
    category: 'schaedlinge',
    categoryLabel: 'Schädlinge',
    emoji: '🦟',
    symptoms: [
      'Kleine schwarze Fliegen am Substrat und um die Pflanze',
      'Larven (weiß, glasig) in den oberen Substratschichten',
      'Verlangsamtes Wachstum',
      'Welkende Sämlinge oder Jungpflanzen',
    ],
    causes: [
      'Dauerhaft feuchte Substratoberfläche',
      'Organisches Material in der Erde',
      'Überwässerung',
      'Befallenes Substrat oder eingeschleppte Fliegen',
    ],
    treatment: [
      'Substratoberfläche abtrocknen lassen zwischen Bewässerungen',
      'Gelbtafeln aufstellen, um erwachsene Fliegen zu fangen',
      'Nematoden (Steinernema feltiae) in das Substrat gießen',
      'BTI (Bacillus thuringiensis israelensis) als Gießmittel verwenden',
      'Quarzsand oder Perlit als oberste Schicht aufbringen',
    ],
    prevention: [
      'Nicht überwässern – Oberfläche zwischen Güssen abtrocknen lassen',
      'Substratoberfläche mit Sand oder Perlit abdecken',
      'Gelbtafeln präventiv aufstellen',
      'Neue Erde vor Gebrauch prüfen',
    ],
    severity: 'mittel',
  },
  {
    id: 's-blattlaeuse',
    name: 'Blattläuse',
    category: 'schaedlinge',
    categoryLabel: 'Schädlinge',
    emoji: '🐛',
    symptoms: [
      'Kolonien von kleinen grünen, schwarzen oder weißen Insekten',
      'Bevorzugt an Triebspitzen und Blattunterseiten',
      'Klebriger Honigtau auf Blättern',
      'Verkrüppeltes neues Wachstum',
      'Rußtaupilz auf dem Honigtau (schwarzer Belag)',
    ],
    causes: [
      'Eingeschleppte Pflanzen oder Stecklinge',
      'Überdüngung mit Stickstoff (weiches Gewebe)',
      'Offene Fenster oder Zuluft ohne Filter',
      'Fehlen natürlicher Feinde',
    ],
    treatment: [
      'Stark befallene Triebe abschneiden',
      'Mit Kaliseife oder Neemöl besprühen',
      'Marienkäfer oder Florfliegen-Larven als Nützlinge einsetzen',
      'Pflanze vorsichtig mit Wasser absprühen',
      'Bei starkem Befall: Pyrethrum-basiertes Mittel verwenden',
    ],
    prevention: [
      'Zuluft filtern',
      'Stickstoff-Düngung nicht übertreiben',
      'Neue Pflanzen in Quarantäne halten',
      'Regelmäßige Kontrolle der Triebspitzen',
    ],
    severity: 'mittel',
  },
  {
    id: 's-thripse',
    name: 'Thripse',
    category: 'schaedlinge',
    categoryLabel: 'Schädlinge',
    emoji: '🪲',
    symptoms: [
      'Silbrige/bronzefarbene Streifen auf Blättern',
      'Kleine dunkle Kotpunkte auf Blattoberflächen',
      'Verformte Blätter und Blüten',
      'Winzige, längliche Insekten (1–2 mm)',
    ],
    causes: [
      'Eingeschleppte Pflanzen',
      'Trockene, warme Bedingungen',
      'Mangelnde Hygiene',
      'Unkraut in der Nähe des Anbaus',
    ],
    treatment: [
      'Blaue Leimtafeln aufhängen (Thripse bevorzugen Blau)',
      'Raubmilben (Amblyseius cucumeris) einsetzen',
      'Neemöl oder Spinosad-basierte Mittel sprühen',
      'Befallene Blätter entfernen',
      'Substratoberfläche behandeln (Puppen leben dort)',
    ],
    prevention: [
      'Blaue Leimtafeln präventiv aufhängen',
      'Luftfeuchtigkeit über 50% halten',
      'Neue Pflanzen in Quarantäne halten',
      'Sauberen Anbauraum pflegen',
    ],
    severity: 'hoch',
  },

  // ── Krankheiten ───────────────────────────────────────────────
  {
    id: 'k-mehltau',
    name: 'Mehltau',
    category: 'krankheiten',
    categoryLabel: 'Krankheiten',
    emoji: '🤍',
    symptoms: [
      'Weißer, pudriger Belag auf Blattoberseiten',
      'Befallene Blätter werden gelb und sterben ab',
      'Beginnt oft an älteren, inneren Blättern',
      'Kann sich auf Stängel und Blüten ausbreiten',
    ],
    causes: [
      'Hohe Luftfeuchtigkeit (über 60%) bei schlechter Belüftung',
      'Zu wenig Luftzirkulation',
      'Temperaturschwankungen (Tag/Nacht)',
      'Dichte Bepflanzung ohne Entlaubung',
    ],
    treatment: [
      'Befallene Blätter sofort entfernen und entsorgen',
      'Kalium-Bikarbonat-Lösung sprühen (1 TL/Liter + Tropfen Seife)',
      'Milch-Wasser-Gemisch (1:9) als Blattspray',
      'Luftzirkulation deutlich verbessern',
      'Luftfeuchtigkeit auf unter 50% senken',
    ],
    prevention: [
      'Gute Luftzirkulation mit Ventilatoren sicherstellen',
      'Luftfeuchtigkeit unter 55% halten',
      'Pflanze regelmäßig entlauben (Lollipop/Defoliation)',
      'Abstand zwischen Pflanzen einhalten',
    ],
    severity: 'hoch',
  },
  {
    id: 'k-wurzelfaeule',
    name: 'Wurzelfäule',
    category: 'krankheiten',
    categoryLabel: 'Krankheiten',
    emoji: '🦠',
    symptoms: [
      'Braune, matschige Wurzeln (statt weiß/cremefarben)',
      'Fauliger Geruch aus dem Wurzelbereich',
      'Pflanze welkt trotz feuchtem Substrat',
      'Verlangsamtes Wachstum, gelbliche Blätter',
    ],
    causes: [
      'Überwässerung / Staunässe',
      'Schlechte Drainage',
      'Zu hohe Wassertemperatur (über 24°C bei Hydro)',
      'Pythium- oder Fusarium-Pilze',
    ],
    treatment: [
      'Bewässerung sofort reduzieren',
      'Befallene Wurzeln vorsichtig abschneiden',
      'Wurzeln in Wasserstoffperoxid-Lösung (3%, 1:4 mit Wasser) tauchen',
      'In frisches, steriles Substrat umtopfen',
      'Enzym- oder Mykorrhiza-Produkte verwenden',
    ],
    prevention: [
      'Substrat zwischen Bewässerungen gut abtrocknen lassen',
      'Gute Drainage sicherstellen (Perlite, Blähton)',
      'Wassertemperatur bei Hydro unter 22°C halten',
      'Saubere Töpfe und steriles Substrat verwenden',
    ],
    severity: 'kritisch',
  },
  {
    id: 'k-botrytis',
    name: 'Botrytis (Grauschimmel)',
    category: 'krankheiten',
    categoryLabel: 'Krankheiten',
    emoji: '🌫️',
    symptoms: [
      'Grauer, flauschiger Schimmel auf Blüten',
      'Braune, absterbende Stellen in den Buds',
      'Blätter nahe der Blüte werden gelb und welken',
      'Befallene Buds fühlen sich matschig an',
    ],
    causes: [
      'Hohe Luftfeuchtigkeit (über 60%) während der Blüte',
      'Schlechte Luftzirkulation',
      'Dichte, kompakte Blütenstruktur',
      'Verletzungen am Pflanzenmaterial',
    ],
    treatment: [
      'Befallene Buds sofort großzügig herausschneiden',
      'Luftfeuchtigkeit auf unter 45% senken',
      'Starke Luftzirkulation rund um die Pflanzen',
      'Temperatur stabil halten, Schwankungen vermeiden',
      'Nicht mehr über die Pflanzen sprühen',
    ],
    prevention: [
      'Luftfeuchtigkeit in der Blüte unter 50% halten',
      'Ventilatoren für Luftbewegung einsetzen',
      'Pflanze entlauben, um Luftfluss zu verbessern',
      'Verletzungen vermeiden, sauberes Werkzeug verwenden',
    ],
    severity: 'kritisch',
  },
  {
    id: 'k-septoria',
    name: 'Septoria (Blattfleckenkrankheit)',
    category: 'krankheiten',
    categoryLabel: 'Krankheiten',
    emoji: '🟡',
    symptoms: [
      'Braune/gelbe runde Flecken mit dunklem Rand',
      'Beginnt an den unteren Blättern',
      'Flecken können kleine schwarze Punkte enthalten (Fruchtkörper)',
      'Befallene Blätter trocknen aus und fallen ab',
    ],
    causes: [
      'Hohe Luftfeuchtigkeit und Nässe auf den Blättern',
      'Schlechte Luftzirkulation',
      'Sporen im Boden oder von befallenen Pflanzen',
      'Warme, feuchte Bedingungen (20–25°C)',
    ],
    treatment: [
      'Befallene Blätter sofort entfernen und entsorgen',
      'Nicht von oben gießen, Blätter trocken halten',
      'Kupferbasiertes Fungizid als Blattspray (nur Veg-Phase)',
      'Neemöl-Lösung als natürliche Alternative',
      'Luftzirkulation verbessern',
    ],
    prevention: [
      'Untere Blätter, die den Boden berühren, entfernen',
      'Für gute Luftzirkulation sorgen',
      'Blätter beim Gießen nicht benetzen',
      'Sauberes Substrat und Hygiene im Anbauraum',
    ],
    severity: 'mittel',
  },

  // ── Umweltprobleme ────────────────────────────────────────────
  {
    id: 'u-hitzestress',
    name: 'Hitzestress',
    category: 'umweltprobleme',
    categoryLabel: 'Umweltprobleme',
    emoji: '🌡️',
    symptoms: [
      'Blätter rollen sich nach oben (Taco-Form)',
      'Braune, trockene Blattränder',
      'Blätter fühlen sich trocken und papierartig an',
      'Übermäßiges Strecken (bei jungen Pflanzen)',
      'Fox-Tailing an Blüten (abnormales Wachstum)',
    ],
    causes: [
      'Temperatur über 30°C',
      'Lampe zu nah an den Pflanzen',
      'Schlechte Belüftung / Abluft',
      'Unzureichende Kühlung im Anbauraum',
    ],
    treatment: [
      'Temperatur auf 22–28°C senken',
      'Lampenabstand vergrößern',
      'Abluft verstärken oder Klimaanlage einsetzen',
      'Nachts den Lichtzyklus verschieben (Licht in kühleren Stunden)',
      'Silica-Zusatz kann Hitzeresistenz erhöhen',
    ],
    prevention: [
      'Temperatur kontinuierlich überwachen (Min/Max-Thermometer)',
      'Lampenabstand gemäß Herstellerangaben einhalten',
      'Ausreichende Abluft und Zuluft installieren',
      'Klimaanlage für heiße Sommermonate einplanen',
    ],
    severity: 'mittel',
  },
  {
    id: 'u-lichtbrand',
    name: 'Lichtbrand',
    category: 'umweltprobleme',
    categoryLabel: 'Umweltprobleme',
    emoji: '☀️',
    symptoms: [
      'Bleaching/Weißfärbung der OBERSTEN Blätter (nächste zur Lampe)',
      'Folgt dem LICHTMUSTER, nicht der Pflanzenstruktur – Schlüssel zur Erkennung!',
      'Blätter werden papierartig/knusprig',
      'Bei LED: kann auch bei NIEDRIGEN Temperaturen auftreten!',
      'Buds können unnatürlich weiß bleichen – sieht "cool" aus, ist aber Schaden',
    ],
    causes: [
      'Lampe zu nah an den Pflanzen',
      'PPFD >1000 µmol/m²/s für die meisten Sorten zu viel',
      'Bei LED: Hitze und Licht NICHT korreliert – immer PPFD/DLI prüfen!',
      'Plötzliche Erhöhung der Lichtintensität oder Umtopfen näher an Lampe',
    ],
    treatment: [
      'Lampenabstand sofort vergrößern (mind. 5–10 cm mehr)',
      'LED-Dimmer reduzieren (falls vorhanden)',
      'PAR/PPFD messen – Ziel: 600–900 µmol/m²/s',
      'Gebleichte Blätter erholen sich NICHT – entfernen falls tot',
    ],
    prevention: [
      'PPFD-Meter verwenden – nicht nur nach Temperatur gehen (besonders bei LED!)',
      'Herstellerempfehlungen für Lampenabstand befolgen',
      'Lichtintensität schrittweise steigern',
      'Nach dem Stretch Lampenabstand neu anpassen',
    ],
    severity: 'mittel',
  },
  {
    id: 'u-ueberwaesserung',
    name: 'Überwässerung',
    category: 'umweltprobleme',
    categoryLabel: 'Umweltprobleme',
    emoji: '💧',
    symptoms: [
      'Blätter hängen schlaff herunter (drooping)',
      'Blätter fühlen sich fest und prall an',
      'Gelbliche Verfärbung',
      'Topf fühlt sich schwer an',
      'Langsames Wachstum',
    ],
    causes: [
      'Zu häufiges Gießen',
      'Schlechte Drainage im Topf',
      'Topf zu groß für die Pflanze',
      'Verdichtetes Substrat ohne Perlit/Blähton',
    ],
    treatment: [
      'Sofort mit dem Gießen aufhören, bis Substrat abgetrocknet',
      'Topf anheben – erst wieder gießen, wenn er sich leicht anfühlt',
      'Drainage prüfen und ggf. verbessern',
      'Bei verdichtetem Substrat: vorsichtig Perlit untermischen oder umtopfen',
    ],
    prevention: [
      'Lift-Test: Topf anheben, um Feuchtigkeit einzuschätzen',
      'Finger-Test: erst gießen, wenn obere 2–3 cm trocken sind',
      'Drainagelöcher und Untersetzer verwenden',
      'Perlit oder Blähton ins Substrat mischen (20–30%)',
    ],
    severity: 'mittel',
  },
  {
    id: 'u-unterwaesserung',
    name: 'Unterwässerung',
    category: 'umweltprobleme',
    categoryLabel: 'Umweltprobleme',
    emoji: '🏜️',
    symptoms: [
      'Blätter hängen schlaff und dünn herunter',
      'Blätter fühlen sich trocken und papierartig an',
      'Substrat ist komplett trocken und zieht sich vom Topfrand zurück',
      'Topf fühlt sich sehr leicht an',
      'Pflanze erholt sich schnell nach dem Gießen',
    ],
    causes: [
      'Zu selten gegossen',
      'Topf zu klein für die Pflanze',
      'Hohe Temperaturen erhöhen den Wasserverbrauch',
      'Substrat hydrophob (trockene Kokos oder Torf)',
    ],
    treatment: [
      'Langsam und gründlich gießen, bis Wasser aus dem Drainage-Loch läuft',
      'Bei hydrophobem Substrat: Topf in Wasser stellen und von unten aufsaugen lassen',
      'Tropfen eines Netzmittels ins Gießwasser geben',
      'Pflanze sollte sich innerhalb von Stunden erholen',
    ],
    prevention: [
      'Regelmäßigen Gießrhythmus etablieren',
      'Passende Topfgröße wählen',
      'Mulchschicht auf dem Substrat kann Verdunstung reduzieren',
      'Bei Hitze häufiger kontrollieren',
    ],
    severity: 'niedrig',
  },
  {
    id: 'u-windburn',
    name: 'Windburn (Windstress)',
    category: 'umweltprobleme',
    categoryLabel: 'Umweltprobleme',
    emoji: '💨',
    symptoms: [
      'Klauen/Krallenbildung NUR AUF EINER SEITE der Pflanze (ASYMMETRISCH!)',
      'Verdickte Stängel auf der Windseite',
      'Trockene, knusprige Blattränder nur auf der betroffenen Seite',
      'Gegenüberliegende Seite sieht völlig normal aus',
      'Eventuell Wachstumsverzögerung auf der Windseite',
    ],
    causes: [
      'Ventilator zu stark und/oder zu nah an der Pflanze',
      'Ventilator nicht oszillierend (Dauerwind auf eine Stelle)',
      'Zuluft direkt auf Pflanze gerichtet',
      'Junge Pflanzen/Sämlinge sind besonders empfindlich',
    ],
    treatment: [
      'Ventilator weiter weg stellen oder Stufe reduzieren',
      'Oszillation einschalten (Ventilator muss schwenken)',
      'Indirekte Luftzirkulation: Ventilator gegen Wand richten',
      'Leicht beschädigte Blätter erholen sich meist von selbst',
      'Bei schwerer Schädigung: betroffene Blätter entfernen',
    ],
    prevention: [
      'Ventilator IMMER auf Oszillation stellen',
      'Mindestabstand 30–50 cm zur nächsten Pflanze',
      'Leichte, indirekte Brise statt starkem Direktwind',
      'Tipp: Asymmetrie unterscheidet von N-Toxizität (symmetrisch) und Hitzestress (Taco oben)',
    ],
    severity: 'niedrig',
  },
  {
    id: 'u-ph-probleme',
    name: 'pH-Probleme',
    category: 'umweltprobleme',
    categoryLabel: 'Umweltprobleme',
    emoji: '⚗️',
    symptoms: [
      'Mehrere Mangelerscheinungen gleichzeitig (Lockout)',
      'Fleckige Verfärbungen auf verschiedenen Blättern',
      'Wachstumsstillstand trotz ausreichender Düngung',
      'Braune Flecken, Vergilbung und Nekrose gemischt',
    ],
    causes: [
      'pH-Wert des Gießwassers nicht korrekt eingestellt',
      'pH-Drift im Substrat über die Zeit',
      'Salzaufbau im Substrat verschiebt den pH',
      'Falsches pH-Ziel für das verwendete Substrat',
    ],
    treatment: [
      'pH-Wert des Gießwassers messen und korrigieren',
      'Erde: pH 6.0–7.0, Kokos/Hydro: pH 5.5–6.5',
      'Substrat mit korrektem pH-Wasser spülen (Flush)',
      'Nach dem Flush mit frischer, pH-korrigierter Nährlösung gießen',
    ],
    prevention: [
      'pH-Wert bei jeder Bewässerung messen',
      'pH-Meter regelmäßig kalibrieren',
      'EC/PPM überwachen, um Salzaufbau zu erkennen',
      'Runoff-pH und -EC messen, um Substratwerte zu prüfen',
    ],
    severity: 'hoch',
  },
];
