export type LibraryCategory = 'naehrstoffmangel' | 'naehrstoffueberschuss' | 'schaedlinge' | 'krankheiten' | 'umweltprobleme';
export type LibrarySeverity = 'niedrig' | 'mittel' | 'hoch' | 'kritisch';

export interface LibraryEntry {
  id: string;
  name: string;
  category: LibraryCategory;
  categoryLabel: string;
  emoji: string;
  symptoms: string[];
  causes: string[];
  treatment: string[];
  prevention: string[];
  severity: LibrarySeverity;
}

export const categoryLabels: Record<LibraryCategory, string> = {
  naehrstoffmangel: 'Nährstoffmangel',
  naehrstoffueberschuss: 'Nährstoffüberschuss',
  schaedlinge: 'Schädlinge',
  krankheiten: 'Krankheiten',
  umweltprobleme: 'Umweltprobleme',
};

export const categoryColors: Record<LibraryCategory, string> = {
  naehrstoffmangel: '#FBBF24',
  naehrstoffueberschuss: '#FB923C',
  schaedlinge: '#F87171',
  krankheiten: '#A78BFA',
  umweltprobleme: '#38BDF8',
};

export const severityColors: Record<LibrarySeverity, string> = {
  niedrig: '#4ADE80',
  mittel: '#FBBF24',
  hoch: '#FB923C',
  kritisch: '#F87171',
};

export const libraryEntries: LibraryEntry[] = [
  // ── Nährstoffmangel ──────────────────────────────────────────
  {
    id: 'n-stickstoff',
    name: 'Stickstoffmangel (N)',
    category: 'naehrstoffmangel',
    categoryLabel: 'Nährstoffmangel',
    emoji: '🍂',
    symptoms: [
      'Vergilbung der unteren/älteren Blätter',
      'Langsames Wachstum',
      'Blätter werden hellgrün bis gelb',
      'Betroffene Blätter fallen ab',
    ],
    causes: [
      'Zu wenig Stickstoff in der Nährlösung',
      'pH-Wert außerhalb des optimalen Bereichs (6.0–7.0 Erde)',
      'Überwässerung blockiert die Aufnahme',
      'Wurzelprobleme',
    ],
    treatment: [
      'Stickstoffreichen Dünger verabreichen',
      'pH-Wert auf 6.0–6.5 (Erde) bzw. 5.5–6.0 (Hydro) korrigieren',
      'Leicht betroffene Blätter an der Pflanze lassen',
      'Stark vergilbte Blätter entfernen',
    ],
    prevention: [
      'Regelmäßig den pH-Wert kontrollieren',
      'Ausgewogenen Düngeplan einhalten',
      'EC/PPM-Werte überwachen',
      'Auf gesunde Wurzeln achten',
    ],
    severity: 'mittel',
  },
  {
    id: 'n-phosphor',
    name: 'Phosphormangel (P)',
    category: 'naehrstoffmangel',
    categoryLabel: 'Nährstoffmangel',
    emoji: '🍆',
    symptoms: [
      'Violette/rötliche Verfärbung der Stängel',
      'Dunkelgrüne bis bläuliche Blätter',
      'Langsames Wachstum und kleine Blätter',
      'Braune Flecken auf älteren Blättern',
    ],
    causes: [
      'Zu wenig Phosphor im Dünger',
      'pH-Wert zu hoch oder zu niedrig',
      'Kalte Temperaturen hemmen die Phosphoraufnahme',
      'Verdichtetes Substrat',
    ],
    treatment: [
      'Phosphorreichen Dünger (Blütedünger) geben',
      'pH-Wert auf 6.2–7.0 (Erde) korrigieren',
      'Bodentemperatur über 15°C halten',
      'Mykorrhiza-Pilze können die Aufnahme verbessern',
    ],
    prevention: [
      'Ausgewogenen Düngeplan verwenden',
      'Bodentemperatur überwachen',
      'pH-Wert regelmäßig prüfen',
      'Gute Drainage sicherstellen',
    ],
    severity: 'mittel',
  },
  {
    id: 'n-kalium',
    name: 'Kaliummangel (K)',
    category: 'naehrstoffmangel',
    categoryLabel: 'Nährstoffmangel',
    emoji: '🍁',
    symptoms: [
      'Braune, verbrannte Blattränder',
      'Blätter rollen sich nach oben',
      'Vergilbung zwischen den Blattadern',
      'Schwache Stängel und langsames Wachstum',
    ],
    causes: [
      'Zu wenig Kalium in der Nährlösung',
      'pH-Wert außerhalb des optimalen Bereichs',
      'Übermäßige Kalzium- oder Magnesiumzufuhr blockiert Kalium',
      'Überwässerung',
    ],
    treatment: [
      'Kaliumreichen Dünger verwenden',
      'pH-Wert auf 6.0–7.0 (Erde) korrigieren',
      'Kalzium/Magnesium-Verhältnis prüfen',
      'Bewässerung optimieren',
    ],
    prevention: [
      'Ausgewogenes Nährstoffverhältnis einhalten',
      'Regelmäßige pH-Kontrolle',
      'Nicht überwässern',
      'Qualitativ hochwertigen Dünger verwenden',
    ],
    severity: 'mittel',
  },
  {
    id: 'n-kalzium',
    name: 'Kalziummangel (Ca)',
    category: 'naehrstoffmangel',
    categoryLabel: 'Nährstoffmangel',
    emoji: '🟤',
    symptoms: [
      'Braune/rostfarbene Flecken auf Blättern',
      'Deformiertes neues Wachstum',
      'Blattspitzen kräuseln sich',
      'Brüchige Stängel',
    ],
    causes: [
      'Zu wenig Kalzium im Gießwasser',
      'Niedriger pH-Wert (unter 6.0)',
      'Hohe Luftfeuchtigkeit reduziert Transpiration',
      'Übermäßiges Kalium blockiert Kalziumaufnahme',
    ],
    treatment: [
      'CalMag-Zusatz verwenden',
      'pH-Wert auf 6.2–6.5 (Erde) anheben',
      'Luftfeuchtigkeit auf 40–60% senken',
      'Für gute Luftzirkulation sorgen',
    ],
    prevention: [
      'CalMag regelmäßig zur Nährlösung hinzufügen',
      'pH-Wert stabil halten',
      'Luftfeuchtigkeit kontrollieren',
      'Wasserqualität prüfen (Osmosewasser braucht CalMag)',
    ],
    severity: 'mittel',
  },
  {
    id: 'n-magnesium',
    name: 'Magnesiummangel (Mg)',
    category: 'naehrstoffmangel',
    categoryLabel: 'Nährstoffmangel',
    emoji: '💛',
    symptoms: [
      'Vergilbung zwischen den Blattadern (Interkostalchlorose)',
      'Beginnt an den unteren/mittleren Blättern',
      'Blattadern bleiben grün',
      'Blätter können sich nach oben einrollen',
    ],
    causes: [
      'Zu wenig Magnesium in der Nährlösung',
      'pH-Wert zu niedrig (unter 6.0)',
      'Überschuss an Kalium oder Kalzium',
      'Kaltes Wurzelmilieu',
    ],
    treatment: [
      'CalMag-Zusatz oder Bittersalz (Epsomsalz) verwenden',
      'pH-Wert auf 6.0–6.5 korrigieren',
      'Blattspray mit Bittersalz (1 TL/Liter) als Soforthilfe',
      'Kalium-Dosierung überprüfen',
    ],
    prevention: [
      'CalMag regelmäßig verwenden',
      'pH-Wert im optimalen Bereich halten',
      'Nährstoffverhältnisse beachten',
      'Substrattemperatur über 18°C halten',
    ],
    severity: 'mittel',
  },
  {
    id: 'n-eisen',
    name: 'Eisenmangel (Fe)',
    category: 'naehrstoffmangel',
    categoryLabel: 'Nährstoffmangel',
    emoji: '🌿',
    symptoms: [
      'Vergilbung der neuen/oberen Blätter',
      'Blattadern bleiben grün (Chlorose)',
      'Junge Blätter können fast weiß werden',
      'Verlangsamtes Wachstum der Triebspitzen',
    ],
    causes: [
      'pH-Wert zu hoch (über 7.0)',
      'Überschuss an Phosphor, Mangan oder Zink',
      'Überwässerung / schlechte Drainage',
      'Kaltes Substrat',
    ],
    treatment: [
      'pH-Wert auf 5.8–6.5 senken',
      'Eisenchelat (EDDHA oder DTPA) verwenden',
      'Drainage verbessern',
      'Phosphor-Dosierung reduzieren',
    ],
    prevention: [
      'pH-Wert stabil im optimalen Bereich halten',
      'Chelatiertes Eisen im Dünger verwenden',
      'Nicht überwässern',
      'Gute Drainage sicherstellen',
    ],
    severity: 'mittel',
  },

  // ── Schädlinge ────────────────────────────────────────────────
  {
    id: 's-spinnmilben',
    name: 'Spinnmilben',
    category: 'schaedlinge',
    categoryLabel: 'Schädlinge',
    emoji: '🕷️',
    symptoms: [
      'Winzige helle Punkte (Stippen) auf der Blattoberseite',
      'Feine Spinnweben an Blattunterseiten und Triebspitzen',
      'Gelbe oder bronzefarbene Verfärbungen',
      'Bei starkem Befall: Blätter trocknen aus und fallen ab',
    ],
    causes: [
      'Trockene, heiße Umgebung (über 27°C, unter 40% Luftfeuchtigkeit)',
      'Eingeschleppte Pflanzen oder Klone',
      'Mangelnde Hygiene im Anbauraum',
      'Schwache, gestresste Pflanzen sind anfälliger',
    ],
    treatment: [
      'Blattunterseiten mit Neemöl-Lösung besprühen (alle 3 Tage)',
      'Raubmilben (Phytoseiulus persimilis) als Nützlinge einsetzen',
      'Temperatur senken und Luftfeuchtigkeit auf 50–60% erhöhen',
      'Stark befallene Blätter entfernen und entsorgen',
      'Bei starkem Befall: Kaliseife oder Pyrethrum verwenden',
    ],
    prevention: [
      'Luftfeuchtigkeit über 50% halten',
      'Temperatur unter 28°C halten',
      'Neue Pflanzen in Quarantäne halten',
      'Regelmäßig Blattunterseiten kontrollieren',
      'Gute Luftzirkulation sicherstellen',
    ],
    severity: 'hoch',
  },
  {
    id: 's-trauermuecken',
    name: 'Trauermücken',
    category: 'schaedlinge',
    categoryLabel: 'Schädlinge',
    emoji: '🦟',
    symptoms: [
      'Kleine schwarze Fliegen am Substrat und um die Pflanze',
      'Larven (weiß, glasig) in den oberen Substratschichten',
      'Verlangsamtes Wachstum',
      'Welkende Sämlinge oder Jungpflanzen',
    ],
    causes: [
      'Dauerhaft feuchte Substratoberfläche',
      'Organisches Material in der Erde',
      'Überwässerung',
      'Befallenes Substrat oder eingeschleppte Fliegen',
    ],
    treatment: [
      'Substratoberfläche abtrocknen lassen zwischen Bewässerungen',
      'Gelbtafeln aufstellen, um erwachsene Fliegen zu fangen',
      'Nematoden (Steinernema feltiae) in das Substrat gießen',
      'BTI (Bacillus thuringiensis israelensis) als Gießmittel verwenden',
      'Quarzsand oder Perlit als oberste Schicht aufbringen',
    ],
    prevention: [
      'Nicht überwässern – Oberfläche zwischen Güssen abtrocknen lassen',
      'Substratoberfläche mit Sand oder Perlit abdecken',
      'Gelbtafeln präventiv aufstellen',
      'Neue Erde vor Gebrauch prüfen',
    ],
    severity: 'mittel',
  },
  {
    id: 's-blattlaeuse',
    name: 'Blattläuse',
    category: 'schaedlinge',
    categoryLabel: 'Schädlinge',
    emoji: '🐛',
    symptoms: [
      'Kolonien von kleinen grünen, schwarzen oder weißen Insekten',
      'Bevorzugt an Triebspitzen und Blattunterseiten',
      'Klebriger Honigtau auf Blättern',
      'Verkrüppeltes neues Wachstum',
      'Rußtaupilz auf dem Honigtau (schwarzer Belag)',
    ],
    causes: [
      'Eingeschleppte Pflanzen oder Stecklinge',
      'Überdüngung mit Stickstoff (weiches Gewebe)',
      'Offene Fenster oder Zuluft ohne Filter',
      'Fehlen natürlicher Feinde',
    ],
    treatment: [
      'Stark befallene Triebe abschneiden',
      'Mit Kaliseife oder Neemöl besprühen',
      'Marienkäfer oder Florfliegen-Larven als Nützlinge einsetzen',
      'Pflanze vorsichtig mit Wasser absprühen',
      'Bei starkem Befall: Pyrethrum-basiertes Mittel verwenden',
    ],
    prevention: [
      'Zuluft filtern',
      'Stickstoff-Düngung nicht übertreiben',
      'Neue Pflanzen in Quarantäne halten',
      'Regelmäßige Kontrolle der Triebspitzen',
    ],
    severity: 'mittel',
  },
  {
    id: 's-thripse',
    name: 'Thripse',
    category: 'schaedlinge',
    categoryLabel: 'Schädlinge',
    emoji: '🪲',
    symptoms: [
      'Silbrige/bronzefarbene Streifen auf Blättern',
      'Kleine dunkle Kotpunkte auf Blattoberflächen',
      'Verformte Blätter und Blüten',
      'Winzige, längliche Insekten (1–2 mm)',
    ],
    causes: [
      'Eingeschleppte Pflanzen',
      'Trockene, warme Bedingungen',
      'Mangelnde Hygiene',
      'Unkraut in der Nähe des Anbaus',
    ],
    treatment: [
      'Blaue Leimtafeln aufhängen (Thripse bevorzugen Blau)',
      'Raubmilben (Amblyseius cucumeris) einsetzen',
      'Neemöl oder Spinosad-basierte Mittel sprühen',
      'Befallene Blätter entfernen',
      'Substratoberfläche behandeln (Puppen leben dort)',
    ],
    prevention: [
      'Blaue Leimtafeln präventiv aufhängen',
      'Luftfeuchtigkeit über 50% halten',
      'Neue Pflanzen in Quarantäne halten',
      'Sauberen Anbauraum pflegen',
    ],
    severity: 'hoch',
  },

  // ── Krankheiten ───────────────────────────────────────────────
  {
    id: 'k-mehltau',
    name: 'Mehltau',
    category: 'krankheiten',
    categoryLabel: 'Krankheiten',
    emoji: '🤍',
    symptoms: [
      'Weißer, pudriger Belag auf Blattoberseiten',
      'Befallene Blätter werden gelb und sterben ab',
      'Beginnt oft an älteren, inneren Blättern',
      'Kann sich auf Stängel und Blüten ausbreiten',
    ],
    causes: [
      'Hohe Luftfeuchtigkeit (über 60%) bei schlechter Belüftung',
      'Zu wenig Luftzirkulation',
      'Temperaturschwankungen (Tag/Nacht)',
      'Dichte Bepflanzung ohne Entlaubung',
    ],
    treatment: [
      'Befallene Blätter sofort entfernen und entsorgen',
      'Kalium-Bikarbonat-Lösung sprühen (1 TL/Liter + Tropfen Seife)',
      'Milch-Wasser-Gemisch (1:9) als Blattspray',
      'Luftzirkulation deutlich verbessern',
      'Luftfeuchtigkeit auf unter 50% senken',
    ],
    prevention: [
      'Gute Luftzirkulation mit Ventilatoren sicherstellen',
      'Luftfeuchtigkeit unter 55% halten',
      'Pflanze regelmäßig entlauben (Lollipop/Defoliation)',
      'Abstand zwischen Pflanzen einhalten',
    ],
    severity: 'hoch',
  },
  {
    id: 'k-wurzelfaeule',
    name: 'Wurzelfäule',
    category: 'krankheiten',
    categoryLabel: 'Krankheiten',
    emoji: '🦠',
    symptoms: [
      'Braune, matschige Wurzeln (statt weiß/cremefarben)',
      'Fauliger Geruch aus dem Wurzelbereich',
      'Pflanze welkt trotz feuchtem Substrat',
      'Verlangsamtes Wachstum, gelbliche Blätter',
    ],
    causes: [
      'Überwässerung / Staunässe',
      'Schlechte Drainage',
      'Zu hohe Wassertemperatur (über 24°C bei Hydro)',
      'Pythium- oder Fusarium-Pilze',
    ],
    treatment: [
      'Bewässerung sofort reduzieren',
      'Befallene Wurzeln vorsichtig abschneiden',
      'Wurzeln in Wasserstoffperoxid-Lösung (3%, 1:4 mit Wasser) tauchen',
      'In frisches, steriles Substrat umtopfen',
      'Enzym- oder Mykorrhiza-Produkte verwenden',
    ],
    prevention: [
      'Substrat zwischen Bewässerungen gut abtrocknen lassen',
      'Gute Drainage sicherstellen (Perlite, Blähton)',
      'Wassertemperatur bei Hydro unter 22°C halten',
      'Saubere Töpfe und steriles Substrat verwenden',
    ],
    severity: 'kritisch',
  },
  {
    id: 'k-botrytis',
    name: 'Botrytis (Grauschimmel)',
    category: 'krankheiten',
    categoryLabel: 'Krankheiten',
    emoji: '🌫️',
    symptoms: [
      'Grauer, flauschiger Schimmel auf Blüten',
      'Braune, absterbende Stellen in den Buds',
      'Blätter nahe der Blüte werden gelb und welken',
      'Befallene Buds fühlen sich matschig an',
    ],
    causes: [
      'Hohe Luftfeuchtigkeit (über 60%) während der Blüte',
      'Schlechte Luftzirkulation',
      'Dichte, kompakte Blütenstruktur',
      'Verletzungen am Pflanzenmaterial',
    ],
    treatment: [
      'Befallene Buds sofort großzügig herausschneiden',
      'Luftfeuchtigkeit auf unter 45% senken',
      'Starke Luftzirkulation rund um die Pflanzen',
      'Temperatur stabil halten, Schwankungen vermeiden',
      'Nicht mehr über die Pflanzen sprühen',
    ],
    prevention: [
      'Luftfeuchtigkeit in der Blüte unter 50% halten',
      'Ventilatoren für Luftbewegung einsetzen',
      'Pflanze entlauben, um Luftfluss zu verbessern',
      'Verletzungen vermeiden, sauberes Werkzeug verwenden',
    ],
    severity: 'kritisch',
  },
  {
    id: 'k-septoria',
    name: 'Septoria (Blattfleckenkrankheit)',
    category: 'krankheiten',
    categoryLabel: 'Krankheiten',
    emoji: '🟡',
    symptoms: [
      'Braune/gelbe runde Flecken mit dunklem Rand',
      'Beginnt an den unteren Blättern',
      'Flecken können kleine schwarze Punkte enthalten (Fruchtkörper)',
      'Befallene Blätter trocknen aus und fallen ab',
    ],
    causes: [
      'Hohe Luftfeuchtigkeit und Nässe auf den Blättern',
      'Schlechte Luftzirkulation',
      'Sporen im Boden oder von befallenen Pflanzen',
      'Warme, feuchte Bedingungen (20–25°C)',
    ],
    treatment: [
      'Befallene Blätter sofort entfernen und entsorgen',
      'Nicht von oben gießen, Blätter trocken halten',
      'Kupferbasiertes Fungizid als Blattspray (nur Veg-Phase)',
      'Neemöl-Lösung als natürliche Alternative',
      'Luftzirkulation verbessern',
    ],
    prevention: [
      'Untere Blätter, die den Boden berühren, entfernen',
      'Für gute Luftzirkulation sorgen',
      'Blätter beim Gießen nicht benetzen',
      'Sauberes Substrat und Hygiene im Anbauraum',
    ],
    severity: 'mittel',
  },

  // ── Umweltprobleme ────────────────────────────────────────────
  {
    id: 'u-hitzestress',
    name: 'Hitzestress',
    category: 'umweltprobleme',
    categoryLabel: 'Umweltprobleme',
    emoji: '🌡️',
    symptoms: [
      'Blätter rollen sich nach oben (Taco-Form)',
      'Braune, trockene Blattränder',
      'Blätter fühlen sich trocken und papierartig an',
      'Übermäßiges Strecken (bei jungen Pflanzen)',
      'Fox-Tailing an Blüten (abnormales Wachstum)',
    ],
    causes: [
      'Temperatur über 30°C',
      'Lampe zu nah an den Pflanzen',
      'Schlechte Belüftung / Abluft',
      'Unzureichende Kühlung im Anbauraum',
    ],
    treatment: [
      'Temperatur auf 22–28°C senken',
      'Lampenabstand vergrößern',
      'Abluft verstärken oder Klimaanlage einsetzen',
      'Nachts den Lichtzyklus verschieben (Licht in kühleren Stunden)',
      'Silica-Zusatz kann Hitzeresistenz erhöhen',
    ],
    prevention: [
      'Temperatur kontinuierlich überwachen (Min/Max-Thermometer)',
      'Lampenabstand gemäß Herstellerangaben einhalten',
      'Ausreichende Abluft und Zuluft installieren',
      'Klimaanlage für heiße Sommermonate einplanen',
    ],
    severity: 'mittel',
  },
  {
    id: 'u-lichtbrand',
    name: 'Lichtbrand',
    category: 'umweltprobleme',
    categoryLabel: 'Umweltprobleme',
    emoji: '☀️',
    symptoms: [
      'Gebleichte/weiße Blattspitzen und -oberseiten',
      'Gelblich-weiße Verfärbung der oberen Blätter',
      'Nur Pflanzenteile nahe der Lampe betroffen',
      'Buds können unnatürlich bleichen (weiß statt grün)',
    ],
    causes: [
      'Lampe zu nah an den Pflanzen',
      'LED-Leistung zu hoch eingestellt',
      'Plötzliche Erhöhung der Lichtintensität',
      'Ungleichmäßige Lichtverteilung',
    ],
    treatment: [
      'Lampenabstand sofort vergrößern (mind. 5–10 cm mehr)',
      'LED-Dimmer reduzieren (falls vorhanden)',
      'Gebleichte Blätter können sich nicht erholen – entfernen falls tot',
      'Pflanze beobachten, ob neue Schäden auftreten',
    ],
    prevention: [
      'Herstellerempfehlungen für Lampenabstand befolgen',
      'Lichtintensität schrittweise steigern',
      'Lux- oder PPFD-Meter verwenden',
      'Pflanzen gleichmäßig im Lichtkegel platzieren',
    ],
    severity: 'mittel',
  },
  {
    id: 'u-ueberwaesserung',
    name: 'Überwässerung',
    category: 'umweltprobleme',
    categoryLabel: 'Umweltprobleme',
    emoji: '💧',
    symptoms: [
      'Blätter hängen schlaff herunter (drooping)',
      'Blätter fühlen sich fest und prall an',
      'Gelbliche Verfärbung',
      'Topf fühlt sich schwer an',
      'Langsames Wachstum',
    ],
    causes: [
      'Zu häufiges Gießen',
      'Schlechte Drainage im Topf',
      'Topf zu groß für die Pflanze',
      'Verdichtetes Substrat ohne Perlit/Blähton',
    ],
    treatment: [
      'Sofort mit dem Gießen aufhören, bis Substrat abgetrocknet',
      'Topf anheben – erst wieder gießen, wenn er sich leicht anfühlt',
      'Drainage prüfen und ggf. verbessern',
      'Bei verdichtetem Substrat: vorsichtig Perlit untermischen oder umtopfen',
    ],
    prevention: [
      'Lift-Test: Topf anheben, um Feuchtigkeit einzuschätzen',
      'Finger-Test: erst gießen, wenn obere 2–3 cm trocken sind',
      'Drainagelöcher und Untersetzer verwenden',
      'Perlit oder Blähton ins Substrat mischen (20–30%)',
    ],
    severity: 'mittel',
  },
  {
    id: 'u-unterwaesserung',
    name: 'Unterwässerung',
    category: 'umweltprobleme',
    categoryLabel: 'Umweltprobleme',
    emoji: '🏜️',
    symptoms: [
      'Blätter hängen schlaff und dünn herunter',
      'Blätter fühlen sich trocken und papierartig an',
      'Substrat ist komplett trocken und zieht sich vom Topfrand zurück',
      'Topf fühlt sich sehr leicht an',
      'Pflanze erholt sich schnell nach dem Gießen',
    ],
    causes: [
      'Zu selten gegossen',
      'Topf zu klein für die Pflanze',
      'Hohe Temperaturen erhöhen den Wasserverbrauch',
      'Substrat hydrophob (trockene Kokos oder Torf)',
    ],
    treatment: [
      'Langsam und gründlich gießen, bis Wasser aus dem Drainage-Loch läuft',
      'Bei hydrophobem Substrat: Topf in Wasser stellen und von unten aufsaugen lassen',
      'Tropfen eines Netzmittels ins Gießwasser geben',
      'Pflanze sollte sich innerhalb von Stunden erholen',
    ],
    prevention: [
      'Regelmäßigen Gießrhythmus etablieren',
      'Passende Topfgröße wählen',
      'Mulchschicht auf dem Substrat kann Verdunstung reduzieren',
      'Bei Hitze häufiger kontrollieren',
    ],
    severity: 'niedrig',
  },
  {
    id: 'u-ph-probleme',
    name: 'pH-Probleme',
    category: 'umweltprobleme',
    categoryLabel: 'Umweltprobleme',
    emoji: '⚗️',
    symptoms: [
      'Mehrere Mangelerscheinungen gleichzeitig (Lockout)',
      'Fleckige Verfärbungen auf verschiedenen Blättern',
      'Wachstumsstillstand trotz ausreichender Düngung',
      'Braune Flecken, Vergilbung und Nekrose gemischt',
    ],
    causes: [
      'pH-Wert des Gießwassers nicht korrekt eingestellt',
      'pH-Drift im Substrat über die Zeit',
      'Salzaufbau im Substrat verschiebt den pH',
      'Falsches pH-Ziel für das verwendete Substrat',
    ],
    treatment: [
      'pH-Wert des Gießwassers messen und korrigieren',
      'Erde: pH 6.0–7.0, Kokos/Hydro: pH 5.5–6.5',
      'Substrat mit korrektem pH-Wasser spülen (Flush)',
      'Nach dem Flush mit frischer, pH-korrigierter Nährlösung gießen',
    ],
    prevention: [
      'pH-Wert bei jeder Bewässerung messen',
      'pH-Meter regelmäßig kalibrieren',
      'EC/PPM überwachen, um Salzaufbau zu erkennen',
      'Runoff-pH und -EC messen, um Substratwerte zu prüfen',
    ],
    severity: 'hoch',
  },
];
