import { Question } from '../types';

export const questions: Question[] = [
  // === Pflanze ===
  {
    id: 'growthPhase',
    section: 'Pflanze',
    question: 'In welcher Wachstumsphase befindet sich die Pflanze?',
    type: 'select',
    options: ['Keimling', 'Vegetativ', 'Blüte', 'Spätblüte'],
  },
  {
    id: 'plantAgeWeeks',
    section: 'Pflanze',
    question: 'Wie alt ist die Pflanze (in Wochen)?',
    type: 'number',
    min: 1,
    max: 52,
    step: 1,
    unit: 'Wochen',
    placeholder: 'z.B. 6',
  },
  {
    id: 'affectedAreas',
    section: 'Pflanze',
    question: 'Welche Bereiche sind betroffen?',
    type: 'multi-select',
    options: ['Obere Blätter', 'Untere Blätter', 'Mittlere Blätter', 'Alle Blätter', 'Stängel', 'Wurzeln'],
    hint: 'Mehrfachauswahl möglich',
  },

  // === Substrat & Wasser ===
  {
    id: 'substrateType',
    section: 'Substrat & Wasser',
    question: 'Welches Substrat verwendest du?',
    type: 'select',
    options: ['Erde', 'Kokos', 'Hydro', 'Perlite-Mix', 'Sonstige'],
  },
  {
    id: 'substrateTempCelsius',
    section: 'Substrat & Wasser',
    question: 'Wie warm ist das Substrat (°C)?',
    type: 'number',
    min: 5,
    max: 40,
    step: 1,
    unit: '°C',
    placeholder: 'z.B. 22',
    hint: 'Falls bekannt – beeinflusst die Nährstoffaufnahme',
  },
  {
    id: 'phFeed',
    section: 'Substrat & Wasser',
    question: 'pH-Wert der Nährlösung (Feed)?',
    type: 'number',
    min: 3,
    max: 9,
    step: 0.1,
    placeholder: 'z.B. 6.2',
  },
  {
    id: 'phRunoff',
    section: 'Substrat & Wasser',
    question: 'pH-Wert des Ablaufwassers (Runoff)?',
    type: 'number',
    min: 3,
    max: 9,
    step: 0.1,
    placeholder: 'z.B. 6.0',
    hint: 'Falls gemessen',
  },
  {
    id: 'ecPpm',
    section: 'Substrat & Wasser',
    question: 'EC/PPM-Wert der Nährlösung?',
    type: 'number',
    min: 0,
    max: 3000,
    step: 50,
    unit: 'PPM',
    placeholder: 'z.B. 800',
  },

  // === Umgebung ===
  {
    id: 'roomTempCelsius',
    section: 'Umgebung',
    question: 'Raumtemperatur (°C)?',
    type: 'number',
    min: 10,
    max: 45,
    step: 1,
    unit: '°C',
    placeholder: 'z.B. 25',
  },
  {
    id: 'humidityPercent',
    section: 'Umgebung',
    question: 'Luftfeuchtigkeit (%)?',
    type: 'number',
    min: 10,
    max: 100,
    step: 5,
    unit: '%',
    placeholder: 'z.B. 55',
  },
  {
    id: 'lightType',
    section: 'Umgebung',
    question: 'Welche Beleuchtung verwendest du?',
    type: 'select',
    options: ['LED', 'NDL/HPS', 'MH', 'CFL', 'Sonnenlicht', 'Sonstige'],
  },
  {
    id: 'lightDistanceCm',
    section: 'Umgebung',
    question: 'Abstand der Lampe zur Pflanze (cm)?',
    type: 'number',
    min: 5,
    max: 200,
    step: 5,
    unit: 'cm',
    placeholder: 'z.B. 40',
  },

  // === Kontext ===
  {
    id: 'wateringFrequency',
    section: 'Kontext',
    question: 'Wie oft gießt du?',
    type: 'text',
    placeholder: 'z.B. Alle 2 Tage, wenn Topf leicht ist',
  },
  {
    id: 'fertilizerDetails',
    section: 'Kontext',
    question: 'Welchen Dünger verwendest du?',
    type: 'text',
    placeholder: 'z.B. BioBizz Grow + Bloom, halbe Dosis',
  },
  {
    id: 'symptomDurationDays',
    section: 'Kontext',
    question: 'Seit wie vielen Tagen zeigen sich die Symptome?',
    type: 'number',
    min: 1,
    max: 90,
    step: 1,
    unit: 'Tage',
    placeholder: 'z.B. 3',
  },
  {
    id: 'recentChanges',
    section: 'Kontext',
    question: 'Gab es kürzlich Änderungen am Setup?',
    type: 'text',
    placeholder: 'z.B. Neue Lampe installiert, Dünger gewechselt...',
    hint: 'Alles was sich in den letzten 1-2 Wochen geändert hat',
  },
];

export const sections = ['Pflanze', 'Substrat & Wasser', 'Umgebung', 'Kontext'];
