services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - api
    restart: unless-stopped

  api:
    build: ./server
    env_file:
      - .env.server
    environment:
      - DOMAIN=https://leafscan.de
    volumes:
      - leafscan-data:/app/data
    restart: unless-stopped

volumes:
  leafscan-data:
